// Code generated by go-bindata.
// sources:
// dict/ipadict.aa
// dict/ipadict.ab
// dict/ipadict.ac
// dict/ipadict.ad
// dict/ipadict.ae
// dict/ipadict.af
// dict/ipadict.ag
// dict/ipadict.ah
// dict/ipadict.ai
// dict/ipadict.aj
// dict/ipadict.ak
// dict/ipadict.al
// dict/ipadict.am
// dict/ipadict.an
// dict/ipadict.ao
// dict/ipadict.ap
// dict/ipadict.aq
// dict/ipadict.ar
// dict/ipadict.as
// dict/ipadict.at
// dict/ipadict.au
// dict/ipadict.av
// dict/ipadict.aw
// dict/ipadict.ax
// dict/ipadict.ay
// dict/ipadict.az
// dict/ipadict.ba
// dict/ipadict.bb
// dict/ipadict.bc
// dict/ipadict.bd
// dict/ipadict.be
// dict/ipadict.bf
// dict/ipadict.bg
// dict/ipadict.bh
// dict/ipadict.bi
// dict/ipadict.bj
// dict/ipadict.bk
// dict/ipadict.bl
// dict/ipadict.bm
// dict/ipadict.bn
// dict/ipadict.bo
// dict/ipadict.bp
// dict/ipadict.bq
// dict/ipadict.br
// dict/ipadict.bs
// dict/ipadict.bt
// dict/ipadict.bu
// dict/ipadict.bv
// dict/ipadict.bw
// dict/ipadict.bx
// dict/ipadict.by
// dict/ipadict.bz
// dict/ipadict.ca
// dict/ipadict.cb
// dict/ipadict.cc
// dict/ipadict.cd
// dict/ipadict.ce
// dict/ipadict.cf
// dict/ipadict.cg
// dict/ipadict.ch
// dict/ipadict.ci
// dict/ipadict.cj
// dict/ipadict.ck
// dict/ipadict.cl
// dict/ipadict.cm
// dict/ipadict.cn
// dict/ipadict.co
// dict/ipadict.cp
// dict/ipadict.cq
// dict/ipadict.cr
// dict/ipadict.cs
// dict/ipadict.ct
// dict/ipadict.cu
// dict/ipadict.cv
// dict/ipadict.cw
// dict/ipadict.cx
// dict/ipadict.cy
// dict/ipadict.cz
// dict/ipadict.da
// dict/ipadict.db
// dict/ipadict.dc
// dict/ipadict.dd
// dict/ipadict.de
// dict/ipadict.df
// dict/ipadict.dg
// dict/ipadict.dh
// dict/ipadict.di
// dict/ipadict.dj
// dict/ipadict.dk
// dict/ipadict.dl
// dict/ipadict.dm
// dict/ipadict.dn
// dict/ipadict.do
// dict/ipadict.dp
// dict/ipadict.dq
// dict/ipadict.dr
// dict/ipadict.ds
// dict/ipadict.dt
// dict/ipadict.du
// dict/ipadict.dv
// dict/ipadict.dw
// dict/ipadict.dx
// dict/ipadict.dy
// dict/ipadict.dz
// dict/ipadict.ea
// dict/ipadict.eb
// dict/ipadict.ec
// dict/ipadict.ed
// dict/ipadict.ee
// dict/ipadict.ef
// dict/ipadict.eg
// dict/ipadict.eh
// dict/ipadict.ei
// dict/ipadict.ej
// dict/ipadict.ek
// dict/ipadict.el
// dict/ipadict.em
// dict/ipadict.en
// dict/ipadict.eo
// dict/ipadict.ep
// dict/ipadict.eq
// dict/ipadict.er
// dict/ipadict.es
// dict/ipadict.et
// dict/ipadict.eu
// dict/ipadict.ev
// dict/ipadict.ew
// dict/ipadict.ex
// dict/ipadict.ey
// dict/ipadict.ez
// dict/ipadict.fa
// dict/ipadict.fb
// dict/ipadict.fc
// dict/ipadict.fd
// dict/ipadict.fe
// dict/ipadict.ff
// dict/ipadict.fg
// dict/ipadict.fh
// dict/ipadict.fi
// dict/ipadict.fj
// dict/ipadict.fk
// dict/ipadict.fl
// dict/ipadict.fm
// dict/ipadict.fn
// dict/ipadict.fo
// dict/ipadict.fp
// dict/ipadict.fq
// dict/ipadict.fr
// dict/ipadict.fs
// dict/ipadict.ft
// dict/ipadict.fu
// dict/ipadict.fv
// dict/ipadict.fw
// dict/ipadict.fx
// dict/ipadict.fy
// dict/ipadict.fz
// dict/ipadict.ga
// dict/ipadict.gb
// dict/ipadict.gc
// dict/ipadict.gd
// dict/ipadict.ge
// dict/ipadict.gf
// dict/ipadict.gg
// dict/ipadict.gh
// dict/ipadict.gi
// dict/ipadict.gj
// dict/ipadict.gk
// dict/ipadict.gl
// dict/ipadict.gm
// dict/ipadict.gn
// dict/ipadict.go
// dict/ipadict.gp
// dict/ipadict.gq
// dict/ipadict.gr
// dict/ipadict.gs
// dict/ipadict.gt
// dict/ipadict.gu
// dict/ipadict.gv
// dict/ipadict.gw
// dict/ipadict.gx
// dict/ipadict.gy
// dict/ipadict.gz
// dict/ipadict.ha
// dict/ipadict.hb
// dict/ipadict.hc
// dict/ipadict.hd
// dict/ipadict.he
// dict/ipadict.hf
// dict/ipadict.hg
// dict/ipadict.hh
// dict/ipadict.hi
// dict/ipadict.hj
// dict/ipadict.hk
// dict/ipadict.hl
// dict/ipadict.hm
// dict/ipadict.hn
// dict/ipadict.ho
// dict/ipadict.hp
// dict/ipadict.hq
// dict/ipadict.hr
// dict/ipadict.hs
// dict/ipadict.ht
// dict/ipadict.hu
// dict/ipadict.hv
// dict/ipadict.hw
// dict/ipadict.hx
// dict/ipadict.hy
// dict/ipadict.hz
// dict/ipadict.ia
// dict/ipadict.ib
// dict/ipadict.ic
// dict/ipadict.id
// dict/ipadict.ie
// dict/ipadict.if
// dict/ipadict.ig
// dict/ipadict.ih
// dict/ipadict.ii
// dict/ipadict.ij
// dict/ipadict.ik
// dict/ipadict.il
// dict/ipadict.im
// dict/ipadict.in
// dict/ipadict.io
// dict/ipadict.ip
// dict/ipadict.iq
// dict/ipadict.ir
// dict/ipadict.is
// dict/ipadict.it
// dict/ipadict.iu
// dict/ipadict.iv
// dict/ipadict.iw
// dict/ipadict.ix
// dict/ipadict.iy
// dict/ipadict.iz
// dict/ipadict.ja
// dict/ipadict.jb
// dict/ipadict.jc
// dict/ipadict.jd
// dict/ipadict.je
// dict/ipadict.jf
// dict/ipadict.jg
// dict/ipadict.jh
// dict/ipadict.ji
// dict/ipadict.jj
// dict/ipadict.jk
// dict/ipadict.jl
// dict/ipadict.jm
// dict/ipadict.jn
// dict/ipadict.jo
// dict/ipadict.jp
// dict/ipadict.jq
// dict/ipadict.jr
// dict/ipadict.js
// dict/ipadict.jt
// dict/ipadict.ju
// dict/ipadict.jv
// dict/ipadict.jw
// dict/ipadict.jx
// dict/ipadict.jy
// dict/ipadict.jz
// dict/ipadict.ka
// dict/ipadict.kb
// dict/ipadict.kc
// dict/ipadict.kd
// dict/ipadict.ke
// dict/ipadict.kf
// dict/ipadict.kg
// dict/ipadict.kh
// dict/ipadict.ki
// dict/ipadict.kj
// dict/ipadict.kk
// dict/ipadict.kl
// dict/ipadict.km
// dict/ipadict.kn
// dict/ipadict.ko
// dict/ipadict.kp
// dict/ipadict.kq
// dict/ipadict.kr
// dict/ipadict.ks
// dict/ipadict.kt
// dict/ipadict.ku
// dict/ipadict.kv
// dict/ipadict.kw
// dict/ipadict.kx
// dict/ipadict.ky
// dict/ipadict.kz
// dict/ipadict.la
// dict/ipadict.lb
// dict/ipadict.lc
// dict/ipadict.ld
// dict/ipadict.le
// dict/ipadict.lf
// dict/ipadict.lg
// dict/ipadict.lh
// dict/ipadict.li
// dict/ipadict.lj
// dict/ipadict.lk
// dict/ipadict.ll
// dict/ipadict.lm
// dict/ipadict.ln
// dict/ipadict.lo
// dict/ipadict.lp
// dict/ipadict.lq
// dict/ipadict.lr
// dict/ipadict.ls
// dict/ipadict.lt
// dict/ipadict.lu
// dict/ipadict.lv
// dict/ipadict.lw
// dict/ipadict.lx
// dict/ipadict.ly
// dict/ipadict.lz
// dict/ipadict.ma
// dict/ipadict.mb
// dict/ipadict.mc
// dict/ipadict.md
// dict/ipadict.me
// dict/ipadict.mf
// dict/ipadict.mg
// dict/ipadict.mh
// dict/ipadict.mi
// dict/ipadict.mj
// dict/ipadict.mk
// dict/ipadict.ml
// dict/ipadict.mm
// dict/ipadict.mn
// dict/ipadict.mo
// dict/ipadict.mp
// dict/ipadict.mq
// dict/ipadict.mr
// dict/ipadict.ms
// dict/ipadict.mt
// dict/ipadict.mu
// dict/ipadict.mv
// dict/ipadict.mw
// dict/ipadict.mx
// dict/ipadict.my
// dict/ipadict.mz
// dict/ipadict.na
// dict/ipadict.nb
// dict/ipadict.nc
// dict/ipadict.nd
// dict/ipadict.ne
// dict/ipadict.nf
// dict/ipadict.ng
// dict/ipadict.nh
// dict/ipadict.ni
// dict/ipadict.nj
// dict/ipadict.nk
// dict/ipadict.nl
// dict/ipadict.nm
// dict/ipadict.nn
// dict/ipadict.no
// dict/ipadict.np
// dict/ipadict.nq
// dict/ipadict.nr
// dict/ipadict.ns
// dict/ipadict.nt
// dict/ipadict.nu
// dict/ipadict.nv
// dict/ipadict.nw
// dict/ipadict.nx
// dict/ipadict.ny
// dict/ipadict.nz
// dict/ipadict.oa
// dict/ipadict.ob
// dict/ipadict.oc
// dict/ipadict.od
// dict/ipadict.oe
// dict/ipadict.of
// dict/ipadict.og
// dict/ipadict.oh
// dict/ipadict.oi
// dict/ipadict.oj
// dict/ipadict.ok
// dict/ipadict.ol
// dict/ipadict.om
// dict/ipadict.on
// dict/ipadict.oo
// dict/ipadict.op
// dict/ipadict.oq
// dict/ipadict.or
// dict/ipadict.os
// dict/ipadict.ot
// dict/ipadict.ou
// dict/ipadict.ov
// dict/ipadict.ow
// dict/ipadict.ox
// dict/ipadict.oy
// dict/ipadict.oz
// dict/ipadict.pa
// dict/ipadict.pb
// dict/ipadict.pc
// dict/ipadict.pd
// dict/ipadict.pe
// dict/ipadict.pf
// dict/ipadict.pg
// dict/ipadict.ph
// dict/ipadict.pi
// dict/ipadict.pj
// dict/ipadict.pk
// dict/ipadict.pl
// dict/ipadict.pm
// dict/ipadict.pn
// dict/ipadict.po
// dict/ipadict.pp
// dict/ipadict.pq
// dict/ipadict.pr
// dict/ipadict.ps
// dict/ipadict.pt
// dict/ipadict.pu
// dict/ipadict.pv
// dict/ipadict.pw
// dict/ipadict.px
// dict/ipadict.py
// dict/ipadict.pz
// dict/ipadict.qa
// dict/ipadict.qb
// dict/ipadict.qc
// dict/ipadict.qd
// dict/ipadict.qe
// dict/ipadict.qf
// dict/ipadict.qg
// dict/ipadict.qh
// dict/ipadict.qi
// dict/ipadict.qj
// DO NOT EDIT!

package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"dict/ipadict.aa": dictIpadictAa,
	"dict/ipadict.ab": dictIpadictAb,
	"dict/ipadict.ac": dictIpadictAc,
	"dict/ipadict.ad": dictIpadictAd,
	"dict/ipadict.ae": dictIpadictAe,
	"dict/ipadict.af": dictIpadictAf,
	"dict/ipadict.ag": dictIpadictAg,
	"dict/ipadict.ah": dictIpadictAh,
	"dict/ipadict.ai": dictIpadictAi,
	"dict/ipadict.aj": dictIpadictAj,
	"dict/ipadict.ak": dictIpadictAk,
	"dict/ipadict.al": dictIpadictAl,
	"dict/ipadict.am": dictIpadictAm,
	"dict/ipadict.an": dictIpadictAn,
	"dict/ipadict.ao": dictIpadictAo,
	"dict/ipadict.ap": dictIpadictAp,
	"dict/ipadict.aq": dictIpadictAq,
	"dict/ipadict.ar": dictIpadictAr,
	"dict/ipadict.as": dictIpadictAs,
	"dict/ipadict.at": dictIpadictAt,
	"dict/ipadict.au": dictIpadictAu,
	"dict/ipadict.av": dictIpadictAv,
	"dict/ipadict.aw": dictIpadictAw,
	"dict/ipadict.ax": dictIpadictAx,
	"dict/ipadict.ay": dictIpadictAy,
	"dict/ipadict.az": dictIpadictAz,
	"dict/ipadict.ba": dictIpadictBa,
	"dict/ipadict.bb": dictIpadictBb,
	"dict/ipadict.bc": dictIpadictBc,
	"dict/ipadict.bd": dictIpadictBd,
	"dict/ipadict.be": dictIpadictBe,
	"dict/ipadict.bf": dictIpadictBf,
	"dict/ipadict.bg": dictIpadictBg,
	"dict/ipadict.bh": dictIpadictBh,
	"dict/ipadict.bi": dictIpadictBi,
	"dict/ipadict.bj": dictIpadictBj,
	"dict/ipadict.bk": dictIpadictBk,
	"dict/ipadict.bl": dictIpadictBl,
	"dict/ipadict.bm": dictIpadictBm,
	"dict/ipadict.bn": dictIpadictBn,
	"dict/ipadict.bo": dictIpadictBo,
	"dict/ipadict.bp": dictIpadictBp,
	"dict/ipadict.bq": dictIpadictBq,
	"dict/ipadict.br": dictIpadictBr,
	"dict/ipadict.bs": dictIpadictBs,
	"dict/ipadict.bt": dictIpadictBt,
	"dict/ipadict.bu": dictIpadictBu,
	"dict/ipadict.bv": dictIpadictBv,
	"dict/ipadict.bw": dictIpadictBw,
	"dict/ipadict.bx": dictIpadictBx,
	"dict/ipadict.by": dictIpadictBy,
	"dict/ipadict.bz": dictIpadictBz,
	"dict/ipadict.ca": dictIpadictCa,
	"dict/ipadict.cb": dictIpadictCb,
	"dict/ipadict.cc": dictIpadictCc,
	"dict/ipadict.cd": dictIpadictCd,
	"dict/ipadict.ce": dictIpadictCe,
	"dict/ipadict.cf": dictIpadictCf,
	"dict/ipadict.cg": dictIpadictCg,
	"dict/ipadict.ch": dictIpadictCh,
	"dict/ipadict.ci": dictIpadictCi,
	"dict/ipadict.cj": dictIpadictCj,
	"dict/ipadict.ck": dictIpadictCk,
	"dict/ipadict.cl": dictIpadictCl,
	"dict/ipadict.cm": dictIpadictCm,
	"dict/ipadict.cn": dictIpadictCn,
	"dict/ipadict.co": dictIpadictCo,
	"dict/ipadict.cp": dictIpadictCp,
	"dict/ipadict.cq": dictIpadictCq,
	"dict/ipadict.cr": dictIpadictCr,
	"dict/ipadict.cs": dictIpadictCs,
	"dict/ipadict.ct": dictIpadictCt,
	"dict/ipadict.cu": dictIpadictCu,
	"dict/ipadict.cv": dictIpadictCv,
	"dict/ipadict.cw": dictIpadictCw,
	"dict/ipadict.cx": dictIpadictCx,
	"dict/ipadict.cy": dictIpadictCy,
	"dict/ipadict.cz": dictIpadictCz,
	"dict/ipadict.da": dictIpadictDa,
	"dict/ipadict.db": dictIpadictDb,
	"dict/ipadict.dc": dictIpadictDc,
	"dict/ipadict.dd": dictIpadictDd,
	"dict/ipadict.de": dictIpadictDe,
	"dict/ipadict.df": dictIpadictDf,
	"dict/ipadict.dg": dictIpadictDg,
	"dict/ipadict.dh": dictIpadictDh,
	"dict/ipadict.di": dictIpadictDi,
	"dict/ipadict.dj": dictIpadictDj,
	"dict/ipadict.dk": dictIpadictDk,
	"dict/ipadict.dl": dictIpadictDl,
	"dict/ipadict.dm": dictIpadictDm,
	"dict/ipadict.dn": dictIpadictDn,
	"dict/ipadict.do": dictIpadictDo,
	"dict/ipadict.dp": dictIpadictDp,
	"dict/ipadict.dq": dictIpadictDq,
	"dict/ipadict.dr": dictIpadictDr,
	"dict/ipadict.ds": dictIpadictDs,
	"dict/ipadict.dt": dictIpadictDt,
	"dict/ipadict.du": dictIpadictDu,
	"dict/ipadict.dv": dictIpadictDv,
	"dict/ipadict.dw": dictIpadictDw,
	"dict/ipadict.dx": dictIpadictDx,
	"dict/ipadict.dy": dictIpadictDy,
	"dict/ipadict.dz": dictIpadictDz,
	"dict/ipadict.ea": dictIpadictEa,
	"dict/ipadict.eb": dictIpadictEb,
	"dict/ipadict.ec": dictIpadictEc,
	"dict/ipadict.ed": dictIpadictEd,
	"dict/ipadict.ee": dictIpadictEe,
	"dict/ipadict.ef": dictIpadictEf,
	"dict/ipadict.eg": dictIpadictEg,
	"dict/ipadict.eh": dictIpadictEh,
	"dict/ipadict.ei": dictIpadictEi,
	"dict/ipadict.ej": dictIpadictEj,
	"dict/ipadict.ek": dictIpadictEk,
	"dict/ipadict.el": dictIpadictEl,
	"dict/ipadict.em": dictIpadictEm,
	"dict/ipadict.en": dictIpadictEn,
	"dict/ipadict.eo": dictIpadictEo,
	"dict/ipadict.ep": dictIpadictEp,
	"dict/ipadict.eq": dictIpadictEq,
	"dict/ipadict.er": dictIpadictEr,
	"dict/ipadict.es": dictIpadictEs,
	"dict/ipadict.et": dictIpadictEt,
	"dict/ipadict.eu": dictIpadictEu,
	"dict/ipadict.ev": dictIpadictEv,
	"dict/ipadict.ew": dictIpadictEw,
	"dict/ipadict.ex": dictIpadictEx,
	"dict/ipadict.ey": dictIpadictEy,
	"dict/ipadict.ez": dictIpadictEz,
	"dict/ipadict.fa": dictIpadictFa,
	"dict/ipadict.fb": dictIpadictFb,
	"dict/ipadict.fc": dictIpadictFc,
	"dict/ipadict.fd": dictIpadictFd,
	"dict/ipadict.fe": dictIpadictFe,
	"dict/ipadict.ff": dictIpadictFf,
	"dict/ipadict.fg": dictIpadictFg,
	"dict/ipadict.fh": dictIpadictFh,
	"dict/ipadict.fi": dictIpadictFi,
	"dict/ipadict.fj": dictIpadictFj,
	"dict/ipadict.fk": dictIpadictFk,
	"dict/ipadict.fl": dictIpadictFl,
	"dict/ipadict.fm": dictIpadictFm,
	"dict/ipadict.fn": dictIpadictFn,
	"dict/ipadict.fo": dictIpadictFo,
	"dict/ipadict.fp": dictIpadictFp,
	"dict/ipadict.fq": dictIpadictFq,
	"dict/ipadict.fr": dictIpadictFr,
	"dict/ipadict.fs": dictIpadictFs,
	"dict/ipadict.ft": dictIpadictFt,
	"dict/ipadict.fu": dictIpadictFu,
	"dict/ipadict.fv": dictIpadictFv,
	"dict/ipadict.fw": dictIpadictFw,
	"dict/ipadict.fx": dictIpadictFx,
	"dict/ipadict.fy": dictIpadictFy,
	"dict/ipadict.fz": dictIpadictFz,
	"dict/ipadict.ga": dictIpadictGa,
	"dict/ipadict.gb": dictIpadictGb,
	"dict/ipadict.gc": dictIpadictGc,
	"dict/ipadict.gd": dictIpadictGd,
	"dict/ipadict.ge": dictIpadictGe,
	"dict/ipadict.gf": dictIpadictGf,
	"dict/ipadict.gg": dictIpadictGg,
	"dict/ipadict.gh": dictIpadictGh,
	"dict/ipadict.gi": dictIpadictGi,
	"dict/ipadict.gj": dictIpadictGj,
	"dict/ipadict.gk": dictIpadictGk,
	"dict/ipadict.gl": dictIpadictGl,
	"dict/ipadict.gm": dictIpadictGm,
	"dict/ipadict.gn": dictIpadictGn,
	"dict/ipadict.go": dictIpadictGo,
	"dict/ipadict.gp": dictIpadictGp,
	"dict/ipadict.gq": dictIpadictGq,
	"dict/ipadict.gr": dictIpadictGr,
	"dict/ipadict.gs": dictIpadictGs,
	"dict/ipadict.gt": dictIpadictGt,
	"dict/ipadict.gu": dictIpadictGu,
	"dict/ipadict.gv": dictIpadictGv,
	"dict/ipadict.gw": dictIpadictGw,
	"dict/ipadict.gx": dictIpadictGx,
	"dict/ipadict.gy": dictIpadictGy,
	"dict/ipadict.gz": dictIpadictGz,
	"dict/ipadict.ha": dictIpadictHa,
	"dict/ipadict.hb": dictIpadictHb,
	"dict/ipadict.hc": dictIpadictHc,
	"dict/ipadict.hd": dictIpadictHd,
	"dict/ipadict.he": dictIpadictHe,
	"dict/ipadict.hf": dictIpadictHf,
	"dict/ipadict.hg": dictIpadictHg,
	"dict/ipadict.hh": dictIpadictHh,
	"dict/ipadict.hi": dictIpadictHi,
	"dict/ipadict.hj": dictIpadictHj,
	"dict/ipadict.hk": dictIpadictHk,
	"dict/ipadict.hl": dictIpadictHl,
	"dict/ipadict.hm": dictIpadictHm,
	"dict/ipadict.hn": dictIpadictHn,
	"dict/ipadict.ho": dictIpadictHo,
	"dict/ipadict.hp": dictIpadictHp,
	"dict/ipadict.hq": dictIpadictHq,
	"dict/ipadict.hr": dictIpadictHr,
	"dict/ipadict.hs": dictIpadictHs,
	"dict/ipadict.ht": dictIpadictHt,
	"dict/ipadict.hu": dictIpadictHu,
	"dict/ipadict.hv": dictIpadictHv,
	"dict/ipadict.hw": dictIpadictHw,
	"dict/ipadict.hx": dictIpadictHx,
	"dict/ipadict.hy": dictIpadictHy,
	"dict/ipadict.hz": dictIpadictHz,
	"dict/ipadict.ia": dictIpadictIa,
	"dict/ipadict.ib": dictIpadictIb,
	"dict/ipadict.ic": dictIpadictIc,
	"dict/ipadict.id": dictIpadictId,
	"dict/ipadict.ie": dictIpadictIe,
	"dict/ipadict.if": dictIpadictIf,
	"dict/ipadict.ig": dictIpadictIg,
	"dict/ipadict.ih": dictIpadictIh,
	"dict/ipadict.ii": dictIpadictIi,
	"dict/ipadict.ij": dictIpadictIj,
	"dict/ipadict.ik": dictIpadictIk,
	"dict/ipadict.il": dictIpadictIl,
	"dict/ipadict.im": dictIpadictIm,
	"dict/ipadict.in": dictIpadictIn,
	"dict/ipadict.io": dictIpadictIo,
	"dict/ipadict.ip": dictIpadictIp,
	"dict/ipadict.iq": dictIpadictIq,
	"dict/ipadict.ir": dictIpadictIr,
	"dict/ipadict.is": dictIpadictIs,
	"dict/ipadict.it": dictIpadictIt,
	"dict/ipadict.iu": dictIpadictIu,
	"dict/ipadict.iv": dictIpadictIv,
	"dict/ipadict.iw": dictIpadictIw,
	"dict/ipadict.ix": dictIpadictIx,
	"dict/ipadict.iy": dictIpadictIy,
	"dict/ipadict.iz": dictIpadictIz,
	"dict/ipadict.ja": dictIpadictJa,
	"dict/ipadict.jb": dictIpadictJb,
	"dict/ipadict.jc": dictIpadictJc,
	"dict/ipadict.jd": dictIpadictJd,
	"dict/ipadict.je": dictIpadictJe,
	"dict/ipadict.jf": dictIpadictJf,
	"dict/ipadict.jg": dictIpadictJg,
	"dict/ipadict.jh": dictIpadictJh,
	"dict/ipadict.ji": dictIpadictJi,
	"dict/ipadict.jj": dictIpadictJj,
	"dict/ipadict.jk": dictIpadictJk,
	"dict/ipadict.jl": dictIpadictJl,
	"dict/ipadict.jm": dictIpadictJm,
	"dict/ipadict.jn": dictIpadictJn,
	"dict/ipadict.jo": dictIpadictJo,
	"dict/ipadict.jp": dictIpadictJp,
	"dict/ipadict.jq": dictIpadictJq,
	"dict/ipadict.jr": dictIpadictJr,
	"dict/ipadict.js": dictIpadictJs,
	"dict/ipadict.jt": dictIpadictJt,
	"dict/ipadict.ju": dictIpadictJu,
	"dict/ipadict.jv": dictIpadictJv,
	"dict/ipadict.jw": dictIpadictJw,
	"dict/ipadict.jx": dictIpadictJx,
	"dict/ipadict.jy": dictIpadictJy,
	"dict/ipadict.jz": dictIpadictJz,
	"dict/ipadict.ka": dictIpadictKa,
	"dict/ipadict.kb": dictIpadictKb,
	"dict/ipadict.kc": dictIpadictKc,
	"dict/ipadict.kd": dictIpadictKd,
	"dict/ipadict.ke": dictIpadictKe,
	"dict/ipadict.kf": dictIpadictKf,
	"dict/ipadict.kg": dictIpadictKg,
	"dict/ipadict.kh": dictIpadictKh,
	"dict/ipadict.ki": dictIpadictKi,
	"dict/ipadict.kj": dictIpadictKj,
	"dict/ipadict.kk": dictIpadictKk,
	"dict/ipadict.kl": dictIpadictKl,
	"dict/ipadict.km": dictIpadictKm,
	"dict/ipadict.kn": dictIpadictKn,
	"dict/ipadict.ko": dictIpadictKo,
	"dict/ipadict.kp": dictIpadictKp,
	"dict/ipadict.kq": dictIpadictKq,
	"dict/ipadict.kr": dictIpadictKr,
	"dict/ipadict.ks": dictIpadictKs,
	"dict/ipadict.kt": dictIpadictKt,
	"dict/ipadict.ku": dictIpadictKu,
	"dict/ipadict.kv": dictIpadictKv,
	"dict/ipadict.kw": dictIpadictKw,
	"dict/ipadict.kx": dictIpadictKx,
	"dict/ipadict.ky": dictIpadictKy,
	"dict/ipadict.kz": dictIpadictKz,
	"dict/ipadict.la": dictIpadictLa,
	"dict/ipadict.lb": dictIpadictLb,
	"dict/ipadict.lc": dictIpadictLc,
	"dict/ipadict.ld": dictIpadictLd,
	"dict/ipadict.le": dictIpadictLe,
	"dict/ipadict.lf": dictIpadictLf,
	"dict/ipadict.lg": dictIpadictLg,
	"dict/ipadict.lh": dictIpadictLh,
	"dict/ipadict.li": dictIpadictLi,
	"dict/ipadict.lj": dictIpadictLj,
	"dict/ipadict.lk": dictIpadictLk,
	"dict/ipadict.ll": dictIpadictLl,
	"dict/ipadict.lm": dictIpadictLm,
	"dict/ipadict.ln": dictIpadictLn,
	"dict/ipadict.lo": dictIpadictLo,
	"dict/ipadict.lp": dictIpadictLp,
	"dict/ipadict.lq": dictIpadictLq,
	"dict/ipadict.lr": dictIpadictLr,
	"dict/ipadict.ls": dictIpadictLs,
	"dict/ipadict.lt": dictIpadictLt,
	"dict/ipadict.lu": dictIpadictLu,
	"dict/ipadict.lv": dictIpadictLv,
	"dict/ipadict.lw": dictIpadictLw,
	"dict/ipadict.lx": dictIpadictLx,
	"dict/ipadict.ly": dictIpadictLy,
	"dict/ipadict.lz": dictIpadictLz,
	"dict/ipadict.ma": dictIpadictMa,
	"dict/ipadict.mb": dictIpadictMb,
	"dict/ipadict.mc": dictIpadictMc,
	"dict/ipadict.md": dictIpadictMd,
	"dict/ipadict.me": dictIpadictMe,
	"dict/ipadict.mf": dictIpadictMf,
	"dict/ipadict.mg": dictIpadictMg,
	"dict/ipadict.mh": dictIpadictMh,
	"dict/ipadict.mi": dictIpadictMi,
	"dict/ipadict.mj": dictIpadictMj,
	"dict/ipadict.mk": dictIpadictMk,
	"dict/ipadict.ml": dictIpadictMl,
	"dict/ipadict.mm": dictIpadictMm,
	"dict/ipadict.mn": dictIpadictMn,
	"dict/ipadict.mo": dictIpadictMo,
	"dict/ipadict.mp": dictIpadictMp,
	"dict/ipadict.mq": dictIpadictMq,
	"dict/ipadict.mr": dictIpadictMr,
	"dict/ipadict.ms": dictIpadictMs,
	"dict/ipadict.mt": dictIpadictMt,
	"dict/ipadict.mu": dictIpadictMu,
	"dict/ipadict.mv": dictIpadictMv,
	"dict/ipadict.mw": dictIpadictMw,
	"dict/ipadict.mx": dictIpadictMx,
	"dict/ipadict.my": dictIpadictMy,
	"dict/ipadict.mz": dictIpadictMz,
	"dict/ipadict.na": dictIpadictNa,
	"dict/ipadict.nb": dictIpadictNb,
	"dict/ipadict.nc": dictIpadictNc,
	"dict/ipadict.nd": dictIpadictNd,
	"dict/ipadict.ne": dictIpadictNe,
	"dict/ipadict.nf": dictIpadictNf,
	"dict/ipadict.ng": dictIpadictNg,
	"dict/ipadict.nh": dictIpadictNh,
	"dict/ipadict.ni": dictIpadictNi,
	"dict/ipadict.nj": dictIpadictNj,
	"dict/ipadict.nk": dictIpadictNk,
	"dict/ipadict.nl": dictIpadictNl,
	"dict/ipadict.nm": dictIpadictNm,
	"dict/ipadict.nn": dictIpadictNn,
	"dict/ipadict.no": dictIpadictNo,
	"dict/ipadict.np": dictIpadictNp,
	"dict/ipadict.nq": dictIpadictNq,
	"dict/ipadict.nr": dictIpadictNr,
	"dict/ipadict.ns": dictIpadictNs,
	"dict/ipadict.nt": dictIpadictNt,
	"dict/ipadict.nu": dictIpadictNu,
	"dict/ipadict.nv": dictIpadictNv,
	"dict/ipadict.nw": dictIpadictNw,
	"dict/ipadict.nx": dictIpadictNx,
	"dict/ipadict.ny": dictIpadictNy,
	"dict/ipadict.nz": dictIpadictNz,
	"dict/ipadict.oa": dictIpadictOa,
	"dict/ipadict.ob": dictIpadictOb,
	"dict/ipadict.oc": dictIpadictOc,
	"dict/ipadict.od": dictIpadictOd,
	"dict/ipadict.oe": dictIpadictOe,
	"dict/ipadict.of": dictIpadictOf,
	"dict/ipadict.og": dictIpadictOg,
	"dict/ipadict.oh": dictIpadictOh,
	"dict/ipadict.oi": dictIpadictOi,
	"dict/ipadict.oj": dictIpadictOj,
	"dict/ipadict.ok": dictIpadictOk,
	"dict/ipadict.ol": dictIpadictOl,
	"dict/ipadict.om": dictIpadictOm,
	"dict/ipadict.on": dictIpadictOn,
	"dict/ipadict.oo": dictIpadictOo,
	"dict/ipadict.op": dictIpadictOp,
	"dict/ipadict.oq": dictIpadictOq,
	"dict/ipadict.or": dictIpadictOr,
	"dict/ipadict.os": dictIpadictOs,
	"dict/ipadict.ot": dictIpadictOt,
	"dict/ipadict.ou": dictIpadictOu,
	"dict/ipadict.ov": dictIpadictOv,
	"dict/ipadict.ow": dictIpadictOw,
	"dict/ipadict.ox": dictIpadictOx,
	"dict/ipadict.oy": dictIpadictOy,
	"dict/ipadict.oz": dictIpadictOz,
	"dict/ipadict.pa": dictIpadictPa,
	"dict/ipadict.pb": dictIpadictPb,
	"dict/ipadict.pc": dictIpadictPc,
	"dict/ipadict.pd": dictIpadictPd,
	"dict/ipadict.pe": dictIpadictPe,
	"dict/ipadict.pf": dictIpadictPf,
	"dict/ipadict.pg": dictIpadictPg,
	"dict/ipadict.ph": dictIpadictPh,
	"dict/ipadict.pi": dictIpadictPi,
	"dict/ipadict.pj": dictIpadictPj,
	"dict/ipadict.pk": dictIpadictPk,
	"dict/ipadict.pl": dictIpadictPl,
	"dict/ipadict.pm": dictIpadictPm,
	"dict/ipadict.pn": dictIpadictPn,
	"dict/ipadict.po": dictIpadictPo,
	"dict/ipadict.pp": dictIpadictPp,
	"dict/ipadict.pq": dictIpadictPq,
	"dict/ipadict.pr": dictIpadictPr,
	"dict/ipadict.ps": dictIpadictPs,
	"dict/ipadict.pt": dictIpadictPt,
	"dict/ipadict.pu": dictIpadictPu,
	"dict/ipadict.pv": dictIpadictPv,
	"dict/ipadict.pw": dictIpadictPw,
	"dict/ipadict.px": dictIpadictPx,
	"dict/ipadict.py": dictIpadictPy,
	"dict/ipadict.pz": dictIpadictPz,
	"dict/ipadict.qa": dictIpadictQa,
	"dict/ipadict.qb": dictIpadictQb,
	"dict/ipadict.qc": dictIpadictQc,
	"dict/ipadict.qd": dictIpadictQd,
	"dict/ipadict.qe": dictIpadictQe,
	"dict/ipadict.qf": dictIpadictQf,
	"dict/ipadict.qg": dictIpadictQg,
	"dict/ipadict.qh": dictIpadictQh,
	"dict/ipadict.qi": dictIpadictQi,
	"dict/ipadict.qj": dictIpadictQj,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"dict": &bintree{nil, map[string]*bintree{
		"ipadict.aa": &bintree{dictIpadictAa, map[string]*bintree{}},
		"ipadict.ab": &bintree{dictIpadictAb, map[string]*bintree{}},
		"ipadict.ac": &bintree{dictIpadictAc, map[string]*bintree{}},
		"ipadict.ad": &bintree{dictIpadictAd, map[string]*bintree{}},
		"ipadict.ae": &bintree{dictIpadictAe, map[string]*bintree{}},
		"ipadict.af": &bintree{dictIpadictAf, map[string]*bintree{}},
		"ipadict.ag": &bintree{dictIpadictAg, map[string]*bintree{}},
		"ipadict.ah": &bintree{dictIpadictAh, map[string]*bintree{}},
		"ipadict.ai": &bintree{dictIpadictAi, map[string]*bintree{}},
		"ipadict.aj": &bintree{dictIpadictAj, map[string]*bintree{}},
		"ipadict.ak": &bintree{dictIpadictAk, map[string]*bintree{}},
		"ipadict.al": &bintree{dictIpadictAl, map[string]*bintree{}},
		"ipadict.am": &bintree{dictIpadictAm, map[string]*bintree{}},
		"ipadict.an": &bintree{dictIpadictAn, map[string]*bintree{}},
		"ipadict.ao": &bintree{dictIpadictAo, map[string]*bintree{}},
		"ipadict.ap": &bintree{dictIpadictAp, map[string]*bintree{}},
		"ipadict.aq": &bintree{dictIpadictAq, map[string]*bintree{}},
		"ipadict.ar": &bintree{dictIpadictAr, map[string]*bintree{}},
		"ipadict.as": &bintree{dictIpadictAs, map[string]*bintree{}},
		"ipadict.at": &bintree{dictIpadictAt, map[string]*bintree{}},
		"ipadict.au": &bintree{dictIpadictAu, map[string]*bintree{}},
		"ipadict.av": &bintree{dictIpadictAv, map[string]*bintree{}},
		"ipadict.aw": &bintree{dictIpadictAw, map[string]*bintree{}},
		"ipadict.ax": &bintree{dictIpadictAx, map[string]*bintree{}},
		"ipadict.ay": &bintree{dictIpadictAy, map[string]*bintree{}},
		"ipadict.az": &bintree{dictIpadictAz, map[string]*bintree{}},
		"ipadict.ba": &bintree{dictIpadictBa, map[string]*bintree{}},
		"ipadict.bb": &bintree{dictIpadictBb, map[string]*bintree{}},
		"ipadict.bc": &bintree{dictIpadictBc, map[string]*bintree{}},
		"ipadict.bd": &bintree{dictIpadictBd, map[string]*bintree{}},
		"ipadict.be": &bintree{dictIpadictBe, map[string]*bintree{}},
		"ipadict.bf": &bintree{dictIpadictBf, map[string]*bintree{}},
		"ipadict.bg": &bintree{dictIpadictBg, map[string]*bintree{}},
		"ipadict.bh": &bintree{dictIpadictBh, map[string]*bintree{}},
		"ipadict.bi": &bintree{dictIpadictBi, map[string]*bintree{}},
		"ipadict.bj": &bintree{dictIpadictBj, map[string]*bintree{}},
		"ipadict.bk": &bintree{dictIpadictBk, map[string]*bintree{}},
		"ipadict.bl": &bintree{dictIpadictBl, map[string]*bintree{}},
		"ipadict.bm": &bintree{dictIpadictBm, map[string]*bintree{}},
		"ipadict.bn": &bintree{dictIpadictBn, map[string]*bintree{}},
		"ipadict.bo": &bintree{dictIpadictBo, map[string]*bintree{}},
		"ipadict.bp": &bintree{dictIpadictBp, map[string]*bintree{}},
		"ipadict.bq": &bintree{dictIpadictBq, map[string]*bintree{}},
		"ipadict.br": &bintree{dictIpadictBr, map[string]*bintree{}},
		"ipadict.bs": &bintree{dictIpadictBs, map[string]*bintree{}},
		"ipadict.bt": &bintree{dictIpadictBt, map[string]*bintree{}},
		"ipadict.bu": &bintree{dictIpadictBu, map[string]*bintree{}},
		"ipadict.bv": &bintree{dictIpadictBv, map[string]*bintree{}},
		"ipadict.bw": &bintree{dictIpadictBw, map[string]*bintree{}},
		"ipadict.bx": &bintree{dictIpadictBx, map[string]*bintree{}},
		"ipadict.by": &bintree{dictIpadictBy, map[string]*bintree{}},
		"ipadict.bz": &bintree{dictIpadictBz, map[string]*bintree{}},
		"ipadict.ca": &bintree{dictIpadictCa, map[string]*bintree{}},
		"ipadict.cb": &bintree{dictIpadictCb, map[string]*bintree{}},
		"ipadict.cc": &bintree{dictIpadictCc, map[string]*bintree{}},
		"ipadict.cd": &bintree{dictIpadictCd, map[string]*bintree{}},
		"ipadict.ce": &bintree{dictIpadictCe, map[string]*bintree{}},
		"ipadict.cf": &bintree{dictIpadictCf, map[string]*bintree{}},
		"ipadict.cg": &bintree{dictIpadictCg, map[string]*bintree{}},
		"ipadict.ch": &bintree{dictIpadictCh, map[string]*bintree{}},
		"ipadict.ci": &bintree{dictIpadictCi, map[string]*bintree{}},
		"ipadict.cj": &bintree{dictIpadictCj, map[string]*bintree{}},
		"ipadict.ck": &bintree{dictIpadictCk, map[string]*bintree{}},
		"ipadict.cl": &bintree{dictIpadictCl, map[string]*bintree{}},
		"ipadict.cm": &bintree{dictIpadictCm, map[string]*bintree{}},
		"ipadict.cn": &bintree{dictIpadictCn, map[string]*bintree{}},
		"ipadict.co": &bintree{dictIpadictCo, map[string]*bintree{}},
		"ipadict.cp": &bintree{dictIpadictCp, map[string]*bintree{}},
		"ipadict.cq": &bintree{dictIpadictCq, map[string]*bintree{}},
		"ipadict.cr": &bintree{dictIpadictCr, map[string]*bintree{}},
		"ipadict.cs": &bintree{dictIpadictCs, map[string]*bintree{}},
		"ipadict.ct": &bintree{dictIpadictCt, map[string]*bintree{}},
		"ipadict.cu": &bintree{dictIpadictCu, map[string]*bintree{}},
		"ipadict.cv": &bintree{dictIpadictCv, map[string]*bintree{}},
		"ipadict.cw": &bintree{dictIpadictCw, map[string]*bintree{}},
		"ipadict.cx": &bintree{dictIpadictCx, map[string]*bintree{}},
		"ipadict.cy": &bintree{dictIpadictCy, map[string]*bintree{}},
		"ipadict.cz": &bintree{dictIpadictCz, map[string]*bintree{}},
		"ipadict.da": &bintree{dictIpadictDa, map[string]*bintree{}},
		"ipadict.db": &bintree{dictIpadictDb, map[string]*bintree{}},
		"ipadict.dc": &bintree{dictIpadictDc, map[string]*bintree{}},
		"ipadict.dd": &bintree{dictIpadictDd, map[string]*bintree{}},
		"ipadict.de": &bintree{dictIpadictDe, map[string]*bintree{}},
		"ipadict.df": &bintree{dictIpadictDf, map[string]*bintree{}},
		"ipadict.dg": &bintree{dictIpadictDg, map[string]*bintree{}},
		"ipadict.dh": &bintree{dictIpadictDh, map[string]*bintree{}},
		"ipadict.di": &bintree{dictIpadictDi, map[string]*bintree{}},
		"ipadict.dj": &bintree{dictIpadictDj, map[string]*bintree{}},
		"ipadict.dk": &bintree{dictIpadictDk, map[string]*bintree{}},
		"ipadict.dl": &bintree{dictIpadictDl, map[string]*bintree{}},
		"ipadict.dm": &bintree{dictIpadictDm, map[string]*bintree{}},
		"ipadict.dn": &bintree{dictIpadictDn, map[string]*bintree{}},
		"ipadict.do": &bintree{dictIpadictDo, map[string]*bintree{}},
		"ipadict.dp": &bintree{dictIpadictDp, map[string]*bintree{}},
		"ipadict.dq": &bintree{dictIpadictDq, map[string]*bintree{}},
		"ipadict.dr": &bintree{dictIpadictDr, map[string]*bintree{}},
		"ipadict.ds": &bintree{dictIpadictDs, map[string]*bintree{}},
		"ipadict.dt": &bintree{dictIpadictDt, map[string]*bintree{}},
		"ipadict.du": &bintree{dictIpadictDu, map[string]*bintree{}},
		"ipadict.dv": &bintree{dictIpadictDv, map[string]*bintree{}},
		"ipadict.dw": &bintree{dictIpadictDw, map[string]*bintree{}},
		"ipadict.dx": &bintree{dictIpadictDx, map[string]*bintree{}},
		"ipadict.dy": &bintree{dictIpadictDy, map[string]*bintree{}},
		"ipadict.dz": &bintree{dictIpadictDz, map[string]*bintree{}},
		"ipadict.ea": &bintree{dictIpadictEa, map[string]*bintree{}},
		"ipadict.eb": &bintree{dictIpadictEb, map[string]*bintree{}},
		"ipadict.ec": &bintree{dictIpadictEc, map[string]*bintree{}},
		"ipadict.ed": &bintree{dictIpadictEd, map[string]*bintree{}},
		"ipadict.ee": &bintree{dictIpadictEe, map[string]*bintree{}},
		"ipadict.ef": &bintree{dictIpadictEf, map[string]*bintree{}},
		"ipadict.eg": &bintree{dictIpadictEg, map[string]*bintree{}},
		"ipadict.eh": &bintree{dictIpadictEh, map[string]*bintree{}},
		"ipadict.ei": &bintree{dictIpadictEi, map[string]*bintree{}},
		"ipadict.ej": &bintree{dictIpadictEj, map[string]*bintree{}},
		"ipadict.ek": &bintree{dictIpadictEk, map[string]*bintree{}},
		"ipadict.el": &bintree{dictIpadictEl, map[string]*bintree{}},
		"ipadict.em": &bintree{dictIpadictEm, map[string]*bintree{}},
		"ipadict.en": &bintree{dictIpadictEn, map[string]*bintree{}},
		"ipadict.eo": &bintree{dictIpadictEo, map[string]*bintree{}},
		"ipadict.ep": &bintree{dictIpadictEp, map[string]*bintree{}},
		"ipadict.eq": &bintree{dictIpadictEq, map[string]*bintree{}},
		"ipadict.er": &bintree{dictIpadictEr, map[string]*bintree{}},
		"ipadict.es": &bintree{dictIpadictEs, map[string]*bintree{}},
		"ipadict.et": &bintree{dictIpadictEt, map[string]*bintree{}},
		"ipadict.eu": &bintree{dictIpadictEu, map[string]*bintree{}},
		"ipadict.ev": &bintree{dictIpadictEv, map[string]*bintree{}},
		"ipadict.ew": &bintree{dictIpadictEw, map[string]*bintree{}},
		"ipadict.ex": &bintree{dictIpadictEx, map[string]*bintree{}},
		"ipadict.ey": &bintree{dictIpadictEy, map[string]*bintree{}},
		"ipadict.ez": &bintree{dictIpadictEz, map[string]*bintree{}},
		"ipadict.fa": &bintree{dictIpadictFa, map[string]*bintree{}},
		"ipadict.fb": &bintree{dictIpadictFb, map[string]*bintree{}},
		"ipadict.fc": &bintree{dictIpadictFc, map[string]*bintree{}},
		"ipadict.fd": &bintree{dictIpadictFd, map[string]*bintree{}},
		"ipadict.fe": &bintree{dictIpadictFe, map[string]*bintree{}},
		"ipadict.ff": &bintree{dictIpadictFf, map[string]*bintree{}},
		"ipadict.fg": &bintree{dictIpadictFg, map[string]*bintree{}},
		"ipadict.fh": &bintree{dictIpadictFh, map[string]*bintree{}},
		"ipadict.fi": &bintree{dictIpadictFi, map[string]*bintree{}},
		"ipadict.fj": &bintree{dictIpadictFj, map[string]*bintree{}},
		"ipadict.fk": &bintree{dictIpadictFk, map[string]*bintree{}},
		"ipadict.fl": &bintree{dictIpadictFl, map[string]*bintree{}},
		"ipadict.fm": &bintree{dictIpadictFm, map[string]*bintree{}},
		"ipadict.fn": &bintree{dictIpadictFn, map[string]*bintree{}},
		"ipadict.fo": &bintree{dictIpadictFo, map[string]*bintree{}},
		"ipadict.fp": &bintree{dictIpadictFp, map[string]*bintree{}},
		"ipadict.fq": &bintree{dictIpadictFq, map[string]*bintree{}},
		"ipadict.fr": &bintree{dictIpadictFr, map[string]*bintree{}},
		"ipadict.fs": &bintree{dictIpadictFs, map[string]*bintree{}},
		"ipadict.ft": &bintree{dictIpadictFt, map[string]*bintree{}},
		"ipadict.fu": &bintree{dictIpadictFu, map[string]*bintree{}},
		"ipadict.fv": &bintree{dictIpadictFv, map[string]*bintree{}},
		"ipadict.fw": &bintree{dictIpadictFw, map[string]*bintree{}},
		"ipadict.fx": &bintree{dictIpadictFx, map[string]*bintree{}},
		"ipadict.fy": &bintree{dictIpadictFy, map[string]*bintree{}},
		"ipadict.fz": &bintree{dictIpadictFz, map[string]*bintree{}},
		"ipadict.ga": &bintree{dictIpadictGa, map[string]*bintree{}},
		"ipadict.gb": &bintree{dictIpadictGb, map[string]*bintree{}},
		"ipadict.gc": &bintree{dictIpadictGc, map[string]*bintree{}},
		"ipadict.gd": &bintree{dictIpadictGd, map[string]*bintree{}},
		"ipadict.ge": &bintree{dictIpadictGe, map[string]*bintree{}},
		"ipadict.gf": &bintree{dictIpadictGf, map[string]*bintree{}},
		"ipadict.gg": &bintree{dictIpadictGg, map[string]*bintree{}},
		"ipadict.gh": &bintree{dictIpadictGh, map[string]*bintree{}},
		"ipadict.gi": &bintree{dictIpadictGi, map[string]*bintree{}},
		"ipadict.gj": &bintree{dictIpadictGj, map[string]*bintree{}},
		"ipadict.gk": &bintree{dictIpadictGk, map[string]*bintree{}},
		"ipadict.gl": &bintree{dictIpadictGl, map[string]*bintree{}},
		"ipadict.gm": &bintree{dictIpadictGm, map[string]*bintree{}},
		"ipadict.gn": &bintree{dictIpadictGn, map[string]*bintree{}},
		"ipadict.go": &bintree{dictIpadictGo, map[string]*bintree{}},
		"ipadict.gp": &bintree{dictIpadictGp, map[string]*bintree{}},
		"ipadict.gq": &bintree{dictIpadictGq, map[string]*bintree{}},
		"ipadict.gr": &bintree{dictIpadictGr, map[string]*bintree{}},
		"ipadict.gs": &bintree{dictIpadictGs, map[string]*bintree{}},
		"ipadict.gt": &bintree{dictIpadictGt, map[string]*bintree{}},
		"ipadict.gu": &bintree{dictIpadictGu, map[string]*bintree{}},
		"ipadict.gv": &bintree{dictIpadictGv, map[string]*bintree{}},
		"ipadict.gw": &bintree{dictIpadictGw, map[string]*bintree{}},
		"ipadict.gx": &bintree{dictIpadictGx, map[string]*bintree{}},
		"ipadict.gy": &bintree{dictIpadictGy, map[string]*bintree{}},
		"ipadict.gz": &bintree{dictIpadictGz, map[string]*bintree{}},
		"ipadict.ha": &bintree{dictIpadictHa, map[string]*bintree{}},
		"ipadict.hb": &bintree{dictIpadictHb, map[string]*bintree{}},
		"ipadict.hc": &bintree{dictIpadictHc, map[string]*bintree{}},
		"ipadict.hd": &bintree{dictIpadictHd, map[string]*bintree{}},
		"ipadict.he": &bintree{dictIpadictHe, map[string]*bintree{}},
		"ipadict.hf": &bintree{dictIpadictHf, map[string]*bintree{}},
		"ipadict.hg": &bintree{dictIpadictHg, map[string]*bintree{}},
		"ipadict.hh": &bintree{dictIpadictHh, map[string]*bintree{}},
		"ipadict.hi": &bintree{dictIpadictHi, map[string]*bintree{}},
		"ipadict.hj": &bintree{dictIpadictHj, map[string]*bintree{}},
		"ipadict.hk": &bintree{dictIpadictHk, map[string]*bintree{}},
		"ipadict.hl": &bintree{dictIpadictHl, map[string]*bintree{}},
		"ipadict.hm": &bintree{dictIpadictHm, map[string]*bintree{}},
		"ipadict.hn": &bintree{dictIpadictHn, map[string]*bintree{}},
		"ipadict.ho": &bintree{dictIpadictHo, map[string]*bintree{}},
		"ipadict.hp": &bintree{dictIpadictHp, map[string]*bintree{}},
		"ipadict.hq": &bintree{dictIpadictHq, map[string]*bintree{}},
		"ipadict.hr": &bintree{dictIpadictHr, map[string]*bintree{}},
		"ipadict.hs": &bintree{dictIpadictHs, map[string]*bintree{}},
		"ipadict.ht": &bintree{dictIpadictHt, map[string]*bintree{}},
		"ipadict.hu": &bintree{dictIpadictHu, map[string]*bintree{}},
		"ipadict.hv": &bintree{dictIpadictHv, map[string]*bintree{}},
		"ipadict.hw": &bintree{dictIpadictHw, map[string]*bintree{}},
		"ipadict.hx": &bintree{dictIpadictHx, map[string]*bintree{}},
		"ipadict.hy": &bintree{dictIpadictHy, map[string]*bintree{}},
		"ipadict.hz": &bintree{dictIpadictHz, map[string]*bintree{}},
		"ipadict.ia": &bintree{dictIpadictIa, map[string]*bintree{}},
		"ipadict.ib": &bintree{dictIpadictIb, map[string]*bintree{}},
		"ipadict.ic": &bintree{dictIpadictIc, map[string]*bintree{}},
		"ipadict.id": &bintree{dictIpadictId, map[string]*bintree{}},
		"ipadict.ie": &bintree{dictIpadictIe, map[string]*bintree{}},
		"ipadict.if": &bintree{dictIpadictIf, map[string]*bintree{}},
		"ipadict.ig": &bintree{dictIpadictIg, map[string]*bintree{}},
		"ipadict.ih": &bintree{dictIpadictIh, map[string]*bintree{}},
		"ipadict.ii": &bintree{dictIpadictIi, map[string]*bintree{}},
		"ipadict.ij": &bintree{dictIpadictIj, map[string]*bintree{}},
		"ipadict.ik": &bintree{dictIpadictIk, map[string]*bintree{}},
		"ipadict.il": &bintree{dictIpadictIl, map[string]*bintree{}},
		"ipadict.im": &bintree{dictIpadictIm, map[string]*bintree{}},
		"ipadict.in": &bintree{dictIpadictIn, map[string]*bintree{}},
		"ipadict.io": &bintree{dictIpadictIo, map[string]*bintree{}},
		"ipadict.ip": &bintree{dictIpadictIp, map[string]*bintree{}},
		"ipadict.iq": &bintree{dictIpadictIq, map[string]*bintree{}},
		"ipadict.ir": &bintree{dictIpadictIr, map[string]*bintree{}},
		"ipadict.is": &bintree{dictIpadictIs, map[string]*bintree{}},
		"ipadict.it": &bintree{dictIpadictIt, map[string]*bintree{}},
		"ipadict.iu": &bintree{dictIpadictIu, map[string]*bintree{}},
		"ipadict.iv": &bintree{dictIpadictIv, map[string]*bintree{}},
		"ipadict.iw": &bintree{dictIpadictIw, map[string]*bintree{}},
		"ipadict.ix": &bintree{dictIpadictIx, map[string]*bintree{}},
		"ipadict.iy": &bintree{dictIpadictIy, map[string]*bintree{}},
		"ipadict.iz": &bintree{dictIpadictIz, map[string]*bintree{}},
		"ipadict.ja": &bintree{dictIpadictJa, map[string]*bintree{}},
		"ipadict.jb": &bintree{dictIpadictJb, map[string]*bintree{}},
		"ipadict.jc": &bintree{dictIpadictJc, map[string]*bintree{}},
		"ipadict.jd": &bintree{dictIpadictJd, map[string]*bintree{}},
		"ipadict.je": &bintree{dictIpadictJe, map[string]*bintree{}},
		"ipadict.jf": &bintree{dictIpadictJf, map[string]*bintree{}},
		"ipadict.jg": &bintree{dictIpadictJg, map[string]*bintree{}},
		"ipadict.jh": &bintree{dictIpadictJh, map[string]*bintree{}},
		"ipadict.ji": &bintree{dictIpadictJi, map[string]*bintree{}},
		"ipadict.jj": &bintree{dictIpadictJj, map[string]*bintree{}},
		"ipadict.jk": &bintree{dictIpadictJk, map[string]*bintree{}},
		"ipadict.jl": &bintree{dictIpadictJl, map[string]*bintree{}},
		"ipadict.jm": &bintree{dictIpadictJm, map[string]*bintree{}},
		"ipadict.jn": &bintree{dictIpadictJn, map[string]*bintree{}},
		"ipadict.jo": &bintree{dictIpadictJo, map[string]*bintree{}},
		"ipadict.jp": &bintree{dictIpadictJp, map[string]*bintree{}},
		"ipadict.jq": &bintree{dictIpadictJq, map[string]*bintree{}},
		"ipadict.jr": &bintree{dictIpadictJr, map[string]*bintree{}},
		"ipadict.js": &bintree{dictIpadictJs, map[string]*bintree{}},
		"ipadict.jt": &bintree{dictIpadictJt, map[string]*bintree{}},
		"ipadict.ju": &bintree{dictIpadictJu, map[string]*bintree{}},
		"ipadict.jv": &bintree{dictIpadictJv, map[string]*bintree{}},
		"ipadict.jw": &bintree{dictIpadictJw, map[string]*bintree{}},
		"ipadict.jx": &bintree{dictIpadictJx, map[string]*bintree{}},
		"ipadict.jy": &bintree{dictIpadictJy, map[string]*bintree{}},
		"ipadict.jz": &bintree{dictIpadictJz, map[string]*bintree{}},
		"ipadict.ka": &bintree{dictIpadictKa, map[string]*bintree{}},
		"ipadict.kb": &bintree{dictIpadictKb, map[string]*bintree{}},
		"ipadict.kc": &bintree{dictIpadictKc, map[string]*bintree{}},
		"ipadict.kd": &bintree{dictIpadictKd, map[string]*bintree{}},
		"ipadict.ke": &bintree{dictIpadictKe, map[string]*bintree{}},
		"ipadict.kf": &bintree{dictIpadictKf, map[string]*bintree{}},
		"ipadict.kg": &bintree{dictIpadictKg, map[string]*bintree{}},
		"ipadict.kh": &bintree{dictIpadictKh, map[string]*bintree{}},
		"ipadict.ki": &bintree{dictIpadictKi, map[string]*bintree{}},
		"ipadict.kj": &bintree{dictIpadictKj, map[string]*bintree{}},
		"ipadict.kk": &bintree{dictIpadictKk, map[string]*bintree{}},
		"ipadict.kl": &bintree{dictIpadictKl, map[string]*bintree{}},
		"ipadict.km": &bintree{dictIpadictKm, map[string]*bintree{}},
		"ipadict.kn": &bintree{dictIpadictKn, map[string]*bintree{}},
		"ipadict.ko": &bintree{dictIpadictKo, map[string]*bintree{}},
		"ipadict.kp": &bintree{dictIpadictKp, map[string]*bintree{}},
		"ipadict.kq": &bintree{dictIpadictKq, map[string]*bintree{}},
		"ipadict.kr": &bintree{dictIpadictKr, map[string]*bintree{}},
		"ipadict.ks": &bintree{dictIpadictKs, map[string]*bintree{}},
		"ipadict.kt": &bintree{dictIpadictKt, map[string]*bintree{}},
		"ipadict.ku": &bintree{dictIpadictKu, map[string]*bintree{}},
		"ipadict.kv": &bintree{dictIpadictKv, map[string]*bintree{}},
		"ipadict.kw": &bintree{dictIpadictKw, map[string]*bintree{}},
		"ipadict.kx": &bintree{dictIpadictKx, map[string]*bintree{}},
		"ipadict.ky": &bintree{dictIpadictKy, map[string]*bintree{}},
		"ipadict.kz": &bintree{dictIpadictKz, map[string]*bintree{}},
		"ipadict.la": &bintree{dictIpadictLa, map[string]*bintree{}},
		"ipadict.lb": &bintree{dictIpadictLb, map[string]*bintree{}},
		"ipadict.lc": &bintree{dictIpadictLc, map[string]*bintree{}},
		"ipadict.ld": &bintree{dictIpadictLd, map[string]*bintree{}},
		"ipadict.le": &bintree{dictIpadictLe, map[string]*bintree{}},
		"ipadict.lf": &bintree{dictIpadictLf, map[string]*bintree{}},
		"ipadict.lg": &bintree{dictIpadictLg, map[string]*bintree{}},
		"ipadict.lh": &bintree{dictIpadictLh, map[string]*bintree{}},
		"ipadict.li": &bintree{dictIpadictLi, map[string]*bintree{}},
		"ipadict.lj": &bintree{dictIpadictLj, map[string]*bintree{}},
		"ipadict.lk": &bintree{dictIpadictLk, map[string]*bintree{}},
		"ipadict.ll": &bintree{dictIpadictLl, map[string]*bintree{}},
		"ipadict.lm": &bintree{dictIpadictLm, map[string]*bintree{}},
		"ipadict.ln": &bintree{dictIpadictLn, map[string]*bintree{}},
		"ipadict.lo": &bintree{dictIpadictLo, map[string]*bintree{}},
		"ipadict.lp": &bintree{dictIpadictLp, map[string]*bintree{}},
		"ipadict.lq": &bintree{dictIpadictLq, map[string]*bintree{}},
		"ipadict.lr": &bintree{dictIpadictLr, map[string]*bintree{}},
		"ipadict.ls": &bintree{dictIpadictLs, map[string]*bintree{}},
		"ipadict.lt": &bintree{dictIpadictLt, map[string]*bintree{}},
		"ipadict.lu": &bintree{dictIpadictLu, map[string]*bintree{}},
		"ipadict.lv": &bintree{dictIpadictLv, map[string]*bintree{}},
		"ipadict.lw": &bintree{dictIpadictLw, map[string]*bintree{}},
		"ipadict.lx": &bintree{dictIpadictLx, map[string]*bintree{}},
		"ipadict.ly": &bintree{dictIpadictLy, map[string]*bintree{}},
		"ipadict.lz": &bintree{dictIpadictLz, map[string]*bintree{}},
		"ipadict.ma": &bintree{dictIpadictMa, map[string]*bintree{}},
		"ipadict.mb": &bintree{dictIpadictMb, map[string]*bintree{}},
		"ipadict.mc": &bintree{dictIpadictMc, map[string]*bintree{}},
		"ipadict.md": &bintree{dictIpadictMd, map[string]*bintree{}},
		"ipadict.me": &bintree{dictIpadictMe, map[string]*bintree{}},
		"ipadict.mf": &bintree{dictIpadictMf, map[string]*bintree{}},
		"ipadict.mg": &bintree{dictIpadictMg, map[string]*bintree{}},
		"ipadict.mh": &bintree{dictIpadictMh, map[string]*bintree{}},
		"ipadict.mi": &bintree{dictIpadictMi, map[string]*bintree{}},
		"ipadict.mj": &bintree{dictIpadictMj, map[string]*bintree{}},
		"ipadict.mk": &bintree{dictIpadictMk, map[string]*bintree{}},
		"ipadict.ml": &bintree{dictIpadictMl, map[string]*bintree{}},
		"ipadict.mm": &bintree{dictIpadictMm, map[string]*bintree{}},
		"ipadict.mn": &bintree{dictIpadictMn, map[string]*bintree{}},
		"ipadict.mo": &bintree{dictIpadictMo, map[string]*bintree{}},
		"ipadict.mp": &bintree{dictIpadictMp, map[string]*bintree{}},
		"ipadict.mq": &bintree{dictIpadictMq, map[string]*bintree{}},
		"ipadict.mr": &bintree{dictIpadictMr, map[string]*bintree{}},
		"ipadict.ms": &bintree{dictIpadictMs, map[string]*bintree{}},
		"ipadict.mt": &bintree{dictIpadictMt, map[string]*bintree{}},
		"ipadict.mu": &bintree{dictIpadictMu, map[string]*bintree{}},
		"ipadict.mv": &bintree{dictIpadictMv, map[string]*bintree{}},
		"ipadict.mw": &bintree{dictIpadictMw, map[string]*bintree{}},
		"ipadict.mx": &bintree{dictIpadictMx, map[string]*bintree{}},
		"ipadict.my": &bintree{dictIpadictMy, map[string]*bintree{}},
		"ipadict.mz": &bintree{dictIpadictMz, map[string]*bintree{}},
		"ipadict.na": &bintree{dictIpadictNa, map[string]*bintree{}},
		"ipadict.nb": &bintree{dictIpadictNb, map[string]*bintree{}},
		"ipadict.nc": &bintree{dictIpadictNc, map[string]*bintree{}},
		"ipadict.nd": &bintree{dictIpadictNd, map[string]*bintree{}},
		"ipadict.ne": &bintree{dictIpadictNe, map[string]*bintree{}},
		"ipadict.nf": &bintree{dictIpadictNf, map[string]*bintree{}},
		"ipadict.ng": &bintree{dictIpadictNg, map[string]*bintree{}},
		"ipadict.nh": &bintree{dictIpadictNh, map[string]*bintree{}},
		"ipadict.ni": &bintree{dictIpadictNi, map[string]*bintree{}},
		"ipadict.nj": &bintree{dictIpadictNj, map[string]*bintree{}},
		"ipadict.nk": &bintree{dictIpadictNk, map[string]*bintree{}},
		"ipadict.nl": &bintree{dictIpadictNl, map[string]*bintree{}},
		"ipadict.nm": &bintree{dictIpadictNm, map[string]*bintree{}},
		"ipadict.nn": &bintree{dictIpadictNn, map[string]*bintree{}},
		"ipadict.no": &bintree{dictIpadictNo, map[string]*bintree{}},
		"ipadict.np": &bintree{dictIpadictNp, map[string]*bintree{}},
		"ipadict.nq": &bintree{dictIpadictNq, map[string]*bintree{}},
		"ipadict.nr": &bintree{dictIpadictNr, map[string]*bintree{}},
		"ipadict.ns": &bintree{dictIpadictNs, map[string]*bintree{}},
		"ipadict.nt": &bintree{dictIpadictNt, map[string]*bintree{}},
		"ipadict.nu": &bintree{dictIpadictNu, map[string]*bintree{}},
		"ipadict.nv": &bintree{dictIpadictNv, map[string]*bintree{}},
		"ipadict.nw": &bintree{dictIpadictNw, map[string]*bintree{}},
		"ipadict.nx": &bintree{dictIpadictNx, map[string]*bintree{}},
		"ipadict.ny": &bintree{dictIpadictNy, map[string]*bintree{}},
		"ipadict.nz": &bintree{dictIpadictNz, map[string]*bintree{}},
		"ipadict.oa": &bintree{dictIpadictOa, map[string]*bintree{}},
		"ipadict.ob": &bintree{dictIpadictOb, map[string]*bintree{}},
		"ipadict.oc": &bintree{dictIpadictOc, map[string]*bintree{}},
		"ipadict.od": &bintree{dictIpadictOd, map[string]*bintree{}},
		"ipadict.oe": &bintree{dictIpadictOe, map[string]*bintree{}},
		"ipadict.of": &bintree{dictIpadictOf, map[string]*bintree{}},
		"ipadict.og": &bintree{dictIpadictOg, map[string]*bintree{}},
		"ipadict.oh": &bintree{dictIpadictOh, map[string]*bintree{}},
		"ipadict.oi": &bintree{dictIpadictOi, map[string]*bintree{}},
		"ipadict.oj": &bintree{dictIpadictOj, map[string]*bintree{}},
		"ipadict.ok": &bintree{dictIpadictOk, map[string]*bintree{}},
		"ipadict.ol": &bintree{dictIpadictOl, map[string]*bintree{}},
		"ipadict.om": &bintree{dictIpadictOm, map[string]*bintree{}},
		"ipadict.on": &bintree{dictIpadictOn, map[string]*bintree{}},
		"ipadict.oo": &bintree{dictIpadictOo, map[string]*bintree{}},
		"ipadict.op": &bintree{dictIpadictOp, map[string]*bintree{}},
		"ipadict.oq": &bintree{dictIpadictOq, map[string]*bintree{}},
		"ipadict.or": &bintree{dictIpadictOr, map[string]*bintree{}},
		"ipadict.os": &bintree{dictIpadictOs, map[string]*bintree{}},
		"ipadict.ot": &bintree{dictIpadictOt, map[string]*bintree{}},
		"ipadict.ou": &bintree{dictIpadictOu, map[string]*bintree{}},
		"ipadict.ov": &bintree{dictIpadictOv, map[string]*bintree{}},
		"ipadict.ow": &bintree{dictIpadictOw, map[string]*bintree{}},
		"ipadict.ox": &bintree{dictIpadictOx, map[string]*bintree{}},
		"ipadict.oy": &bintree{dictIpadictOy, map[string]*bintree{}},
		"ipadict.oz": &bintree{dictIpadictOz, map[string]*bintree{}},
		"ipadict.pa": &bintree{dictIpadictPa, map[string]*bintree{}},
		"ipadict.pb": &bintree{dictIpadictPb, map[string]*bintree{}},
		"ipadict.pc": &bintree{dictIpadictPc, map[string]*bintree{}},
		"ipadict.pd": &bintree{dictIpadictPd, map[string]*bintree{}},
		"ipadict.pe": &bintree{dictIpadictPe, map[string]*bintree{}},
		"ipadict.pf": &bintree{dictIpadictPf, map[string]*bintree{}},
		"ipadict.pg": &bintree{dictIpadictPg, map[string]*bintree{}},
		"ipadict.ph": &bintree{dictIpadictPh, map[string]*bintree{}},
		"ipadict.pi": &bintree{dictIpadictPi, map[string]*bintree{}},
		"ipadict.pj": &bintree{dictIpadictPj, map[string]*bintree{}},
		"ipadict.pk": &bintree{dictIpadictPk, map[string]*bintree{}},
		"ipadict.pl": &bintree{dictIpadictPl, map[string]*bintree{}},
		"ipadict.pm": &bintree{dictIpadictPm, map[string]*bintree{}},
		"ipadict.pn": &bintree{dictIpadictPn, map[string]*bintree{}},
		"ipadict.po": &bintree{dictIpadictPo, map[string]*bintree{}},
		"ipadict.pp": &bintree{dictIpadictPp, map[string]*bintree{}},
		"ipadict.pq": &bintree{dictIpadictPq, map[string]*bintree{}},
		"ipadict.pr": &bintree{dictIpadictPr, map[string]*bintree{}},
		"ipadict.ps": &bintree{dictIpadictPs, map[string]*bintree{}},
		"ipadict.pt": &bintree{dictIpadictPt, map[string]*bintree{}},
		"ipadict.pu": &bintree{dictIpadictPu, map[string]*bintree{}},
		"ipadict.pv": &bintree{dictIpadictPv, map[string]*bintree{}},
		"ipadict.pw": &bintree{dictIpadictPw, map[string]*bintree{}},
		"ipadict.px": &bintree{dictIpadictPx, map[string]*bintree{}},
		"ipadict.py": &bintree{dictIpadictPy, map[string]*bintree{}},
		"ipadict.pz": &bintree{dictIpadictPz, map[string]*bintree{}},
		"ipadict.qa": &bintree{dictIpadictQa, map[string]*bintree{}},
		"ipadict.qb": &bintree{dictIpadictQb, map[string]*bintree{}},
		"ipadict.qc": &bintree{dictIpadictQc, map[string]*bintree{}},
		"ipadict.qd": &bintree{dictIpadictQd, map[string]*bintree{}},
		"ipadict.qe": &bintree{dictIpadictQe, map[string]*bintree{}},
		"ipadict.qf": &bintree{dictIpadictQf, map[string]*bintree{}},
		"ipadict.qg": &bintree{dictIpadictQg, map[string]*bintree{}},
		"ipadict.qh": &bintree{dictIpadictQh, map[string]*bintree{}},
		"ipadict.qi": &bintree{dictIpadictQi, map[string]*bintree{}},
		"ipadict.qj": &bintree{dictIpadictQj, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

