// Code generated by go-bindata.
// sources:
// dict/mod0/ipa-neologd-dict.aa
// dict/mod0/ipa-neologd-dict.ab
// dict/mod0/ipa-neologd-dict.ac
// dict/mod0/ipa-neologd-dict.ad
// dict/mod0/ipa-neologd-dict.ae
// dict/mod0/ipa-neologd-dict.af
// dict/mod0/ipa-neologd-dict.ag
// dict/mod0/ipa-neologd-dict.ah
// dict/mod0/ipa-neologd-dict.ai
// dict/mod0/ipa-neologd-dict.aj
// dict/mod0/ipa-neologd-dict.ak
// dict/mod0/ipa-neologd-dict.al
// dict/mod0/ipa-neologd-dict.am
// dict/mod0/ipa-neologd-dict.an
// dict/mod0/ipa-neologd-dict.ao
// dict/mod0/ipa-neologd-dict.ap
// dict/mod0/ipa-neologd-dict.aq
// dict/mod0/ipa-neologd-dict.ar
// dict/mod0/ipa-neologd-dict.as
// dict/mod0/ipa-neologd-dict.at
// dict/mod0/ipa-neologd-dict.au
// dict/mod0/ipa-neologd-dict.av
// dict/mod0/ipa-neologd-dict.aw
// dict/mod0/ipa-neologd-dict.ax
// dict/mod0/ipa-neologd-dict.ay
// dict/mod0/ipa-neologd-dict.az
// dict/mod0/ipa-neologd-dict.ba
// dict/mod0/ipa-neologd-dict.bb
// dict/mod0/ipa-neologd-dict.bc
// dict/mod0/ipa-neologd-dict.bd
// dict/mod0/ipa-neologd-dict.be
// dict/mod0/ipa-neologd-dict.bf
// dict/mod0/ipa-neologd-dict.bg
// dict/mod0/ipa-neologd-dict.bh
// dict/mod0/ipa-neologd-dict.bi
// dict/mod0/ipa-neologd-dict.bj
// dict/mod0/ipa-neologd-dict.bk
// dict/mod0/ipa-neologd-dict.bl
// dict/mod0/ipa-neologd-dict.bm
// dict/mod0/ipa-neologd-dict.bn
// dict/mod0/ipa-neologd-dict.bo
// dict/mod0/ipa-neologd-dict.bp
// dict/mod0/ipa-neologd-dict.bq
// dict/mod0/ipa-neologd-dict.br
// dict/mod0/ipa-neologd-dict.bs
// dict/mod0/ipa-neologd-dict.bt
// dict/mod0/ipa-neologd-dict.bu
// dict/mod0/ipa-neologd-dict.bv
// dict/mod0/ipa-neologd-dict.bw
// dict/mod0/ipa-neologd-dict.bx
// dict/mod0/ipa-neologd-dict.by
// dict/mod0/ipa-neologd-dict.bz
// dict/mod0/ipa-neologd-dict.ca
// dict/mod0/ipa-neologd-dict.cb
// dict/mod0/ipa-neologd-dict.cc
// dict/mod0/ipa-neologd-dict.cd
// dict/mod0/ipa-neologd-dict.ce
// dict/mod0/ipa-neologd-dict.cf
// dict/mod0/ipa-neologd-dict.cg
// dict/mod0/ipa-neologd-dict.ch
// dict/mod0/ipa-neologd-dict.ci
// dict/mod0/ipa-neologd-dict.cj
// dict/mod0/ipa-neologd-dict.ck
// dict/mod0/ipa-neologd-dict.cl
// dict/mod0/ipa-neologd-dict.cm
// dict/mod0/ipa-neologd-dict.cn
// dict/mod0/ipa-neologd-dict.co
// dict/mod0/ipa-neologd-dict.cp
// dict/mod0/ipa-neologd-dict.cq
// dict/mod0/ipa-neologd-dict.cr
// dict/mod0/ipa-neologd-dict.cs
// dict/mod0/ipa-neologd-dict.ct
// dict/mod0/ipa-neologd-dict.cu
// dict/mod0/ipa-neologd-dict.cv
// dict/mod0/ipa-neologd-dict.cw
// dict/mod0/ipa-neologd-dict.cx
// dict/mod0/ipa-neologd-dict.cy
// dict/mod0/ipa-neologd-dict.cz
// dict/mod0/ipa-neologd-dict.da
// dict/mod0/ipa-neologd-dict.db
// dict/mod0/ipa-neologd-dict.dc
// dict/mod0/ipa-neologd-dict.dd
// dict/mod0/ipa-neologd-dict.de
// dict/mod0/ipa-neologd-dict.df
// dict/mod0/ipa-neologd-dict.dg
// dict/mod0/ipa-neologd-dict.dh
// dict/mod0/ipa-neologd-dict.di
// dict/mod0/ipa-neologd-dict.dj
// dict/mod0/ipa-neologd-dict.dk
// dict/mod0/ipa-neologd-dict.dl
// dict/mod0/ipa-neologd-dict.dm
// dict/mod0/ipa-neologd-dict.dn
// dict/mod0/ipa-neologd-dict.do
// dict/mod0/ipa-neologd-dict.dp
// dict/mod0/ipa-neologd-dict.dq
// dict/mod0/ipa-neologd-dict.dr
// dict/mod0/ipa-neologd-dict.ds
// dict/mod0/ipa-neologd-dict.dt
// dict/mod0/ipa-neologd-dict.du
// dict/mod0/ipa-neologd-dict.dv
// dict/mod0/ipa-neologd-dict.dw
// dict/mod0/ipa-neologd-dict.dx
// dict/mod0/ipa-neologd-dict.dy
// dict/mod0/ipa-neologd-dict.dz
// dict/mod0/ipa-neologd-dict.ea
// dict/mod0/ipa-neologd-dict.eb
// dict/mod0/ipa-neologd-dict.ec
// dict/mod0/ipa-neologd-dict.ed
// dict/mod0/ipa-neologd-dict.ee
// dict/mod0/ipa-neologd-dict.ef
// dict/mod0/ipa-neologd-dict.eg
// dict/mod0/ipa-neologd-dict.eh
// dict/mod0/ipa-neologd-dict.ei
// dict/mod0/ipa-neologd-dict.ej
// dict/mod0/ipa-neologd-dict.ek
// dict/mod0/ipa-neologd-dict.el
// dict/mod0/ipa-neologd-dict.em
// dict/mod0/ipa-neologd-dict.en
// dict/mod0/ipa-neologd-dict.eo
// dict/mod0/ipa-neologd-dict.ep
// dict/mod0/ipa-neologd-dict.eq
// dict/mod0/ipa-neologd-dict.er
// dict/mod0/ipa-neologd-dict.es
// dict/mod0/ipa-neologd-dict.et
// dict/mod0/ipa-neologd-dict.eu
// dict/mod0/ipa-neologd-dict.ev
// dict/mod0/ipa-neologd-dict.ew
// dict/mod0/ipa-neologd-dict.ex
// dict/mod0/ipa-neologd-dict.ey
// dict/mod0/ipa-neologd-dict.ez
// dict/mod0/ipa-neologd-dict.fa
// dict/mod0/ipa-neologd-dict.fb
// dict/mod0/ipa-neologd-dict.fc
// dict/mod0/ipa-neologd-dict.fd
// dict/mod0/ipa-neologd-dict.fe
// dict/mod0/ipa-neologd-dict.ff
// dict/mod0/ipa-neologd-dict.fg
// dict/mod0/ipa-neologd-dict.fh
// dict/mod0/ipa-neologd-dict.fi
// dict/mod0/ipa-neologd-dict.fj
// dict/mod0/ipa-neologd-dict.fk
// dict/mod0/ipa-neologd-dict.fl
// dict/mod0/ipa-neologd-dict.fm
// dict/mod0/ipa-neologd-dict.fn
// dict/mod0/ipa-neologd-dict.fo
// dict/mod0/ipa-neologd-dict.fp
// dict/mod0/ipa-neologd-dict.fq
// dict/mod0/ipa-neologd-dict.fr
// dict/mod0/ipa-neologd-dict.fs
// dict/mod0/ipa-neologd-dict.ft
// dict/mod0/ipa-neologd-dict.fu
// dict/mod0/ipa-neologd-dict.fv
// dict/mod0/ipa-neologd-dict.fw
// dict/mod0/ipa-neologd-dict.fx
// dict/mod0/ipa-neologd-dict.fy
// dict/mod0/ipa-neologd-dict.fz
// dict/mod0/ipa-neologd-dict.ga
// dict/mod0/ipa-neologd-dict.gb
// dict/mod0/ipa-neologd-dict.gc
// dict/mod0/ipa-neologd-dict.gd
// dict/mod0/ipa-neologd-dict.ge
// dict/mod0/ipa-neologd-dict.gf
// dict/mod0/ipa-neologd-dict.gg
// dict/mod0/ipa-neologd-dict.gh
// dict/mod0/ipa-neologd-dict.gi
// dict/mod0/ipa-neologd-dict.gj
// dict/mod0/ipa-neologd-dict.gk
// dict/mod0/ipa-neologd-dict.gl
// dict/mod0/ipa-neologd-dict.gm
// dict/mod0/ipa-neologd-dict.gn
// dict/mod0/ipa-neologd-dict.go
// dict/mod0/ipa-neologd-dict.gp
// dict/mod0/ipa-neologd-dict.gq
// dict/mod0/ipa-neologd-dict.gr
// dict/mod0/ipa-neologd-dict.gs
// dict/mod0/ipa-neologd-dict.gt
// dict/mod0/ipa-neologd-dict.gu
// dict/mod0/ipa-neologd-dict.gv
// dict/mod0/ipa-neologd-dict.gw
// dict/mod0/ipa-neologd-dict.gx
// dict/mod0/ipa-neologd-dict.gy
// dict/mod0/ipa-neologd-dict.gz
// dict/mod0/ipa-neologd-dict.ha
// dict/mod0/ipa-neologd-dict.hb
// dict/mod0/ipa-neologd-dict.hc
// dict/mod0/ipa-neologd-dict.hd
// dict/mod0/ipa-neologd-dict.he
// dict/mod0/ipa-neologd-dict.hf
// dict/mod0/ipa-neologd-dict.hg
// dict/mod0/ipa-neologd-dict.hh
// dict/mod0/ipa-neologd-dict.hi
// dict/mod0/ipa-neologd-dict.hj
// dict/mod0/ipa-neologd-dict.hk
// dict/mod0/ipa-neologd-dict.hl
// dict/mod0/ipa-neologd-dict.hm
// dict/mod0/ipa-neologd-dict.hn
// dict/mod0/ipa-neologd-dict.ho
// dict/mod0/ipa-neologd-dict.hp
// dict/mod0/ipa-neologd-dict.hq
// dict/mod0/ipa-neologd-dict.hr
// dict/mod0/ipa-neologd-dict.hs
// dict/mod0/ipa-neologd-dict.ht
// dict/mod0/ipa-neologd-dict.hu
// dict/mod0/ipa-neologd-dict.hv
// dict/mod0/ipa-neologd-dict.hw
// dict/mod0/ipa-neologd-dict.hx
// dict/mod0/ipa-neologd-dict.hy
// dict/mod0/ipa-neologd-dict.hz
// dict/mod0/ipa-neologd-dict.ia
// dict/mod0/ipa-neologd-dict.ib
// dict/mod0/ipa-neologd-dict.ic
// dict/mod0/ipa-neologd-dict.id
// dict/mod0/ipa-neologd-dict.ie
// dict/mod0/ipa-neologd-dict.if
// dict/mod0/ipa-neologd-dict.ig
// dict/mod0/ipa-neologd-dict.ih
// dict/mod0/ipa-neologd-dict.ii
// dict/mod0/ipa-neologd-dict.ij
// dict/mod0/ipa-neologd-dict.ik
// dict/mod0/ipa-neologd-dict.il
// dict/mod0/ipa-neologd-dict.im
// dict/mod0/ipa-neologd-dict.in
// dict/mod0/ipa-neologd-dict.io
// dict/mod0/ipa-neologd-dict.ip
// dict/mod0/ipa-neologd-dict.iq
// dict/mod0/ipa-neologd-dict.ir
// dict/mod0/ipa-neologd-dict.is
// dict/mod0/ipa-neologd-dict.it
// dict/mod0/ipa-neologd-dict.iu
// dict/mod0/ipa-neologd-dict.iv
// dict/mod0/ipa-neologd-dict.iw
// dict/mod0/ipa-neologd-dict.ix
// dict/mod0/ipa-neologd-dict.iy
// dict/mod0/ipa-neologd-dict.iz
// dict/mod0/ipa-neologd-dict.ja
// dict/mod0/ipa-neologd-dict.jb
// dict/mod0/ipa-neologd-dict.jc
// dict/mod0/ipa-neologd-dict.jd
// dict/mod0/ipa-neologd-dict.je
// dict/mod0/ipa-neologd-dict.jf
// dict/mod0/ipa-neologd-dict.jg
// dict/mod0/ipa-neologd-dict.jh
// dict/mod0/ipa-neologd-dict.ji
// dict/mod0/ipa-neologd-dict.jj
// dict/mod0/ipa-neologd-dict.jk
// dict/mod0/ipa-neologd-dict.jl
// dict/mod0/ipa-neologd-dict.jm
// dict/mod0/ipa-neologd-dict.jn
// dict/mod0/ipa-neologd-dict.jo
// DO NOT EDIT!

package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"dict/mod0/ipa-neologd-dict.aa": dictMod0IpaNeologdDictAa,
	"dict/mod0/ipa-neologd-dict.ab": dictMod0IpaNeologdDictAb,
	"dict/mod0/ipa-neologd-dict.ac": dictMod0IpaNeologdDictAc,
	"dict/mod0/ipa-neologd-dict.ad": dictMod0IpaNeologdDictAd,
	"dict/mod0/ipa-neologd-dict.ae": dictMod0IpaNeologdDictAe,
	"dict/mod0/ipa-neologd-dict.af": dictMod0IpaNeologdDictAf,
	"dict/mod0/ipa-neologd-dict.ag": dictMod0IpaNeologdDictAg,
	"dict/mod0/ipa-neologd-dict.ah": dictMod0IpaNeologdDictAh,
	"dict/mod0/ipa-neologd-dict.ai": dictMod0IpaNeologdDictAi,
	"dict/mod0/ipa-neologd-dict.aj": dictMod0IpaNeologdDictAj,
	"dict/mod0/ipa-neologd-dict.ak": dictMod0IpaNeologdDictAk,
	"dict/mod0/ipa-neologd-dict.al": dictMod0IpaNeologdDictAl,
	"dict/mod0/ipa-neologd-dict.am": dictMod0IpaNeologdDictAm,
	"dict/mod0/ipa-neologd-dict.an": dictMod0IpaNeologdDictAn,
	"dict/mod0/ipa-neologd-dict.ao": dictMod0IpaNeologdDictAo,
	"dict/mod0/ipa-neologd-dict.ap": dictMod0IpaNeologdDictAp,
	"dict/mod0/ipa-neologd-dict.aq": dictMod0IpaNeologdDictAq,
	"dict/mod0/ipa-neologd-dict.ar": dictMod0IpaNeologdDictAr,
	"dict/mod0/ipa-neologd-dict.as": dictMod0IpaNeologdDictAs,
	"dict/mod0/ipa-neologd-dict.at": dictMod0IpaNeologdDictAt,
	"dict/mod0/ipa-neologd-dict.au": dictMod0IpaNeologdDictAu,
	"dict/mod0/ipa-neologd-dict.av": dictMod0IpaNeologdDictAv,
	"dict/mod0/ipa-neologd-dict.aw": dictMod0IpaNeologdDictAw,
	"dict/mod0/ipa-neologd-dict.ax": dictMod0IpaNeologdDictAx,
	"dict/mod0/ipa-neologd-dict.ay": dictMod0IpaNeologdDictAy,
	"dict/mod0/ipa-neologd-dict.az": dictMod0IpaNeologdDictAz,
	"dict/mod0/ipa-neologd-dict.ba": dictMod0IpaNeologdDictBa,
	"dict/mod0/ipa-neologd-dict.bb": dictMod0IpaNeologdDictBb,
	"dict/mod0/ipa-neologd-dict.bc": dictMod0IpaNeologdDictBc,
	"dict/mod0/ipa-neologd-dict.bd": dictMod0IpaNeologdDictBd,
	"dict/mod0/ipa-neologd-dict.be": dictMod0IpaNeologdDictBe,
	"dict/mod0/ipa-neologd-dict.bf": dictMod0IpaNeologdDictBf,
	"dict/mod0/ipa-neologd-dict.bg": dictMod0IpaNeologdDictBg,
	"dict/mod0/ipa-neologd-dict.bh": dictMod0IpaNeologdDictBh,
	"dict/mod0/ipa-neologd-dict.bi": dictMod0IpaNeologdDictBi,
	"dict/mod0/ipa-neologd-dict.bj": dictMod0IpaNeologdDictBj,
	"dict/mod0/ipa-neologd-dict.bk": dictMod0IpaNeologdDictBk,
	"dict/mod0/ipa-neologd-dict.bl": dictMod0IpaNeologdDictBl,
	"dict/mod0/ipa-neologd-dict.bm": dictMod0IpaNeologdDictBm,
	"dict/mod0/ipa-neologd-dict.bn": dictMod0IpaNeologdDictBn,
	"dict/mod0/ipa-neologd-dict.bo": dictMod0IpaNeologdDictBo,
	"dict/mod0/ipa-neologd-dict.bp": dictMod0IpaNeologdDictBp,
	"dict/mod0/ipa-neologd-dict.bq": dictMod0IpaNeologdDictBq,
	"dict/mod0/ipa-neologd-dict.br": dictMod0IpaNeologdDictBr,
	"dict/mod0/ipa-neologd-dict.bs": dictMod0IpaNeologdDictBs,
	"dict/mod0/ipa-neologd-dict.bt": dictMod0IpaNeologdDictBt,
	"dict/mod0/ipa-neologd-dict.bu": dictMod0IpaNeologdDictBu,
	"dict/mod0/ipa-neologd-dict.bv": dictMod0IpaNeologdDictBv,
	"dict/mod0/ipa-neologd-dict.bw": dictMod0IpaNeologdDictBw,
	"dict/mod0/ipa-neologd-dict.bx": dictMod0IpaNeologdDictBx,
	"dict/mod0/ipa-neologd-dict.by": dictMod0IpaNeologdDictBy,
	"dict/mod0/ipa-neologd-dict.bz": dictMod0IpaNeologdDictBz,
	"dict/mod0/ipa-neologd-dict.ca": dictMod0IpaNeologdDictCa,
	"dict/mod0/ipa-neologd-dict.cb": dictMod0IpaNeologdDictCb,
	"dict/mod0/ipa-neologd-dict.cc": dictMod0IpaNeologdDictCc,
	"dict/mod0/ipa-neologd-dict.cd": dictMod0IpaNeologdDictCd,
	"dict/mod0/ipa-neologd-dict.ce": dictMod0IpaNeologdDictCe,
	"dict/mod0/ipa-neologd-dict.cf": dictMod0IpaNeologdDictCf,
	"dict/mod0/ipa-neologd-dict.cg": dictMod0IpaNeologdDictCg,
	"dict/mod0/ipa-neologd-dict.ch": dictMod0IpaNeologdDictCh,
	"dict/mod0/ipa-neologd-dict.ci": dictMod0IpaNeologdDictCi,
	"dict/mod0/ipa-neologd-dict.cj": dictMod0IpaNeologdDictCj,
	"dict/mod0/ipa-neologd-dict.ck": dictMod0IpaNeologdDictCk,
	"dict/mod0/ipa-neologd-dict.cl": dictMod0IpaNeologdDictCl,
	"dict/mod0/ipa-neologd-dict.cm": dictMod0IpaNeologdDictCm,
	"dict/mod0/ipa-neologd-dict.cn": dictMod0IpaNeologdDictCn,
	"dict/mod0/ipa-neologd-dict.co": dictMod0IpaNeologdDictCo,
	"dict/mod0/ipa-neologd-dict.cp": dictMod0IpaNeologdDictCp,
	"dict/mod0/ipa-neologd-dict.cq": dictMod0IpaNeologdDictCq,
	"dict/mod0/ipa-neologd-dict.cr": dictMod0IpaNeologdDictCr,
	"dict/mod0/ipa-neologd-dict.cs": dictMod0IpaNeologdDictCs,
	"dict/mod0/ipa-neologd-dict.ct": dictMod0IpaNeologdDictCt,
	"dict/mod0/ipa-neologd-dict.cu": dictMod0IpaNeologdDictCu,
	"dict/mod0/ipa-neologd-dict.cv": dictMod0IpaNeologdDictCv,
	"dict/mod0/ipa-neologd-dict.cw": dictMod0IpaNeologdDictCw,
	"dict/mod0/ipa-neologd-dict.cx": dictMod0IpaNeologdDictCx,
	"dict/mod0/ipa-neologd-dict.cy": dictMod0IpaNeologdDictCy,
	"dict/mod0/ipa-neologd-dict.cz": dictMod0IpaNeologdDictCz,
	"dict/mod0/ipa-neologd-dict.da": dictMod0IpaNeologdDictDa,
	"dict/mod0/ipa-neologd-dict.db": dictMod0IpaNeologdDictDb,
	"dict/mod0/ipa-neologd-dict.dc": dictMod0IpaNeologdDictDc,
	"dict/mod0/ipa-neologd-dict.dd": dictMod0IpaNeologdDictDd,
	"dict/mod0/ipa-neologd-dict.de": dictMod0IpaNeologdDictDe,
	"dict/mod0/ipa-neologd-dict.df": dictMod0IpaNeologdDictDf,
	"dict/mod0/ipa-neologd-dict.dg": dictMod0IpaNeologdDictDg,
	"dict/mod0/ipa-neologd-dict.dh": dictMod0IpaNeologdDictDh,
	"dict/mod0/ipa-neologd-dict.di": dictMod0IpaNeologdDictDi,
	"dict/mod0/ipa-neologd-dict.dj": dictMod0IpaNeologdDictDj,
	"dict/mod0/ipa-neologd-dict.dk": dictMod0IpaNeologdDictDk,
	"dict/mod0/ipa-neologd-dict.dl": dictMod0IpaNeologdDictDl,
	"dict/mod0/ipa-neologd-dict.dm": dictMod0IpaNeologdDictDm,
	"dict/mod0/ipa-neologd-dict.dn": dictMod0IpaNeologdDictDn,
	"dict/mod0/ipa-neologd-dict.do": dictMod0IpaNeologdDictDo,
	"dict/mod0/ipa-neologd-dict.dp": dictMod0IpaNeologdDictDp,
	"dict/mod0/ipa-neologd-dict.dq": dictMod0IpaNeologdDictDq,
	"dict/mod0/ipa-neologd-dict.dr": dictMod0IpaNeologdDictDr,
	"dict/mod0/ipa-neologd-dict.ds": dictMod0IpaNeologdDictDs,
	"dict/mod0/ipa-neologd-dict.dt": dictMod0IpaNeologdDictDt,
	"dict/mod0/ipa-neologd-dict.du": dictMod0IpaNeologdDictDu,
	"dict/mod0/ipa-neologd-dict.dv": dictMod0IpaNeologdDictDv,
	"dict/mod0/ipa-neologd-dict.dw": dictMod0IpaNeologdDictDw,
	"dict/mod0/ipa-neologd-dict.dx": dictMod0IpaNeologdDictDx,
	"dict/mod0/ipa-neologd-dict.dy": dictMod0IpaNeologdDictDy,
	"dict/mod0/ipa-neologd-dict.dz": dictMod0IpaNeologdDictDz,
	"dict/mod0/ipa-neologd-dict.ea": dictMod0IpaNeologdDictEa,
	"dict/mod0/ipa-neologd-dict.eb": dictMod0IpaNeologdDictEb,
	"dict/mod0/ipa-neologd-dict.ec": dictMod0IpaNeologdDictEc,
	"dict/mod0/ipa-neologd-dict.ed": dictMod0IpaNeologdDictEd,
	"dict/mod0/ipa-neologd-dict.ee": dictMod0IpaNeologdDictEe,
	"dict/mod0/ipa-neologd-dict.ef": dictMod0IpaNeologdDictEf,
	"dict/mod0/ipa-neologd-dict.eg": dictMod0IpaNeologdDictEg,
	"dict/mod0/ipa-neologd-dict.eh": dictMod0IpaNeologdDictEh,
	"dict/mod0/ipa-neologd-dict.ei": dictMod0IpaNeologdDictEi,
	"dict/mod0/ipa-neologd-dict.ej": dictMod0IpaNeologdDictEj,
	"dict/mod0/ipa-neologd-dict.ek": dictMod0IpaNeologdDictEk,
	"dict/mod0/ipa-neologd-dict.el": dictMod0IpaNeologdDictEl,
	"dict/mod0/ipa-neologd-dict.em": dictMod0IpaNeologdDictEm,
	"dict/mod0/ipa-neologd-dict.en": dictMod0IpaNeologdDictEn,
	"dict/mod0/ipa-neologd-dict.eo": dictMod0IpaNeologdDictEo,
	"dict/mod0/ipa-neologd-dict.ep": dictMod0IpaNeologdDictEp,
	"dict/mod0/ipa-neologd-dict.eq": dictMod0IpaNeologdDictEq,
	"dict/mod0/ipa-neologd-dict.er": dictMod0IpaNeologdDictEr,
	"dict/mod0/ipa-neologd-dict.es": dictMod0IpaNeologdDictEs,
	"dict/mod0/ipa-neologd-dict.et": dictMod0IpaNeologdDictEt,
	"dict/mod0/ipa-neologd-dict.eu": dictMod0IpaNeologdDictEu,
	"dict/mod0/ipa-neologd-dict.ev": dictMod0IpaNeologdDictEv,
	"dict/mod0/ipa-neologd-dict.ew": dictMod0IpaNeologdDictEw,
	"dict/mod0/ipa-neologd-dict.ex": dictMod0IpaNeologdDictEx,
	"dict/mod0/ipa-neologd-dict.ey": dictMod0IpaNeologdDictEy,
	"dict/mod0/ipa-neologd-dict.ez": dictMod0IpaNeologdDictEz,
	"dict/mod0/ipa-neologd-dict.fa": dictMod0IpaNeologdDictFa,
	"dict/mod0/ipa-neologd-dict.fb": dictMod0IpaNeologdDictFb,
	"dict/mod0/ipa-neologd-dict.fc": dictMod0IpaNeologdDictFc,
	"dict/mod0/ipa-neologd-dict.fd": dictMod0IpaNeologdDictFd,
	"dict/mod0/ipa-neologd-dict.fe": dictMod0IpaNeologdDictFe,
	"dict/mod0/ipa-neologd-dict.ff": dictMod0IpaNeologdDictFf,
	"dict/mod0/ipa-neologd-dict.fg": dictMod0IpaNeologdDictFg,
	"dict/mod0/ipa-neologd-dict.fh": dictMod0IpaNeologdDictFh,
	"dict/mod0/ipa-neologd-dict.fi": dictMod0IpaNeologdDictFi,
	"dict/mod0/ipa-neologd-dict.fj": dictMod0IpaNeologdDictFj,
	"dict/mod0/ipa-neologd-dict.fk": dictMod0IpaNeologdDictFk,
	"dict/mod0/ipa-neologd-dict.fl": dictMod0IpaNeologdDictFl,
	"dict/mod0/ipa-neologd-dict.fm": dictMod0IpaNeologdDictFm,
	"dict/mod0/ipa-neologd-dict.fn": dictMod0IpaNeologdDictFn,
	"dict/mod0/ipa-neologd-dict.fo": dictMod0IpaNeologdDictFo,
	"dict/mod0/ipa-neologd-dict.fp": dictMod0IpaNeologdDictFp,
	"dict/mod0/ipa-neologd-dict.fq": dictMod0IpaNeologdDictFq,
	"dict/mod0/ipa-neologd-dict.fr": dictMod0IpaNeologdDictFr,
	"dict/mod0/ipa-neologd-dict.fs": dictMod0IpaNeologdDictFs,
	"dict/mod0/ipa-neologd-dict.ft": dictMod0IpaNeologdDictFt,
	"dict/mod0/ipa-neologd-dict.fu": dictMod0IpaNeologdDictFu,
	"dict/mod0/ipa-neologd-dict.fv": dictMod0IpaNeologdDictFv,
	"dict/mod0/ipa-neologd-dict.fw": dictMod0IpaNeologdDictFw,
	"dict/mod0/ipa-neologd-dict.fx": dictMod0IpaNeologdDictFx,
	"dict/mod0/ipa-neologd-dict.fy": dictMod0IpaNeologdDictFy,
	"dict/mod0/ipa-neologd-dict.fz": dictMod0IpaNeologdDictFz,
	"dict/mod0/ipa-neologd-dict.ga": dictMod0IpaNeologdDictGa,
	"dict/mod0/ipa-neologd-dict.gb": dictMod0IpaNeologdDictGb,
	"dict/mod0/ipa-neologd-dict.gc": dictMod0IpaNeologdDictGc,
	"dict/mod0/ipa-neologd-dict.gd": dictMod0IpaNeologdDictGd,
	"dict/mod0/ipa-neologd-dict.ge": dictMod0IpaNeologdDictGe,
	"dict/mod0/ipa-neologd-dict.gf": dictMod0IpaNeologdDictGf,
	"dict/mod0/ipa-neologd-dict.gg": dictMod0IpaNeologdDictGg,
	"dict/mod0/ipa-neologd-dict.gh": dictMod0IpaNeologdDictGh,
	"dict/mod0/ipa-neologd-dict.gi": dictMod0IpaNeologdDictGi,
	"dict/mod0/ipa-neologd-dict.gj": dictMod0IpaNeologdDictGj,
	"dict/mod0/ipa-neologd-dict.gk": dictMod0IpaNeologdDictGk,
	"dict/mod0/ipa-neologd-dict.gl": dictMod0IpaNeologdDictGl,
	"dict/mod0/ipa-neologd-dict.gm": dictMod0IpaNeologdDictGm,
	"dict/mod0/ipa-neologd-dict.gn": dictMod0IpaNeologdDictGn,
	"dict/mod0/ipa-neologd-dict.go": dictMod0IpaNeologdDictGo,
	"dict/mod0/ipa-neologd-dict.gp": dictMod0IpaNeologdDictGp,
	"dict/mod0/ipa-neologd-dict.gq": dictMod0IpaNeologdDictGq,
	"dict/mod0/ipa-neologd-dict.gr": dictMod0IpaNeologdDictGr,
	"dict/mod0/ipa-neologd-dict.gs": dictMod0IpaNeologdDictGs,
	"dict/mod0/ipa-neologd-dict.gt": dictMod0IpaNeologdDictGt,
	"dict/mod0/ipa-neologd-dict.gu": dictMod0IpaNeologdDictGu,
	"dict/mod0/ipa-neologd-dict.gv": dictMod0IpaNeologdDictGv,
	"dict/mod0/ipa-neologd-dict.gw": dictMod0IpaNeologdDictGw,
	"dict/mod0/ipa-neologd-dict.gx": dictMod0IpaNeologdDictGx,
	"dict/mod0/ipa-neologd-dict.gy": dictMod0IpaNeologdDictGy,
	"dict/mod0/ipa-neologd-dict.gz": dictMod0IpaNeologdDictGz,
	"dict/mod0/ipa-neologd-dict.ha": dictMod0IpaNeologdDictHa,
	"dict/mod0/ipa-neologd-dict.hb": dictMod0IpaNeologdDictHb,
	"dict/mod0/ipa-neologd-dict.hc": dictMod0IpaNeologdDictHc,
	"dict/mod0/ipa-neologd-dict.hd": dictMod0IpaNeologdDictHd,
	"dict/mod0/ipa-neologd-dict.he": dictMod0IpaNeologdDictHe,
	"dict/mod0/ipa-neologd-dict.hf": dictMod0IpaNeologdDictHf,
	"dict/mod0/ipa-neologd-dict.hg": dictMod0IpaNeologdDictHg,
	"dict/mod0/ipa-neologd-dict.hh": dictMod0IpaNeologdDictHh,
	"dict/mod0/ipa-neologd-dict.hi": dictMod0IpaNeologdDictHi,
	"dict/mod0/ipa-neologd-dict.hj": dictMod0IpaNeologdDictHj,
	"dict/mod0/ipa-neologd-dict.hk": dictMod0IpaNeologdDictHk,
	"dict/mod0/ipa-neologd-dict.hl": dictMod0IpaNeologdDictHl,
	"dict/mod0/ipa-neologd-dict.hm": dictMod0IpaNeologdDictHm,
	"dict/mod0/ipa-neologd-dict.hn": dictMod0IpaNeologdDictHn,
	"dict/mod0/ipa-neologd-dict.ho": dictMod0IpaNeologdDictHo,
	"dict/mod0/ipa-neologd-dict.hp": dictMod0IpaNeologdDictHp,
	"dict/mod0/ipa-neologd-dict.hq": dictMod0IpaNeologdDictHq,
	"dict/mod0/ipa-neologd-dict.hr": dictMod0IpaNeologdDictHr,
	"dict/mod0/ipa-neologd-dict.hs": dictMod0IpaNeologdDictHs,
	"dict/mod0/ipa-neologd-dict.ht": dictMod0IpaNeologdDictHt,
	"dict/mod0/ipa-neologd-dict.hu": dictMod0IpaNeologdDictHu,
	"dict/mod0/ipa-neologd-dict.hv": dictMod0IpaNeologdDictHv,
	"dict/mod0/ipa-neologd-dict.hw": dictMod0IpaNeologdDictHw,
	"dict/mod0/ipa-neologd-dict.hx": dictMod0IpaNeologdDictHx,
	"dict/mod0/ipa-neologd-dict.hy": dictMod0IpaNeologdDictHy,
	"dict/mod0/ipa-neologd-dict.hz": dictMod0IpaNeologdDictHz,
	"dict/mod0/ipa-neologd-dict.ia": dictMod0IpaNeologdDictIa,
	"dict/mod0/ipa-neologd-dict.ib": dictMod0IpaNeologdDictIb,
	"dict/mod0/ipa-neologd-dict.ic": dictMod0IpaNeologdDictIc,
	"dict/mod0/ipa-neologd-dict.id": dictMod0IpaNeologdDictId,
	"dict/mod0/ipa-neologd-dict.ie": dictMod0IpaNeologdDictIe,
	"dict/mod0/ipa-neologd-dict.if": dictMod0IpaNeologdDictIf,
	"dict/mod0/ipa-neologd-dict.ig": dictMod0IpaNeologdDictIg,
	"dict/mod0/ipa-neologd-dict.ih": dictMod0IpaNeologdDictIh,
	"dict/mod0/ipa-neologd-dict.ii": dictMod0IpaNeologdDictIi,
	"dict/mod0/ipa-neologd-dict.ij": dictMod0IpaNeologdDictIj,
	"dict/mod0/ipa-neologd-dict.ik": dictMod0IpaNeologdDictIk,
	"dict/mod0/ipa-neologd-dict.il": dictMod0IpaNeologdDictIl,
	"dict/mod0/ipa-neologd-dict.im": dictMod0IpaNeologdDictIm,
	"dict/mod0/ipa-neologd-dict.in": dictMod0IpaNeologdDictIn,
	"dict/mod0/ipa-neologd-dict.io": dictMod0IpaNeologdDictIo,
	"dict/mod0/ipa-neologd-dict.ip": dictMod0IpaNeologdDictIp,
	"dict/mod0/ipa-neologd-dict.iq": dictMod0IpaNeologdDictIq,
	"dict/mod0/ipa-neologd-dict.ir": dictMod0IpaNeologdDictIr,
	"dict/mod0/ipa-neologd-dict.is": dictMod0IpaNeologdDictIs,
	"dict/mod0/ipa-neologd-dict.it": dictMod0IpaNeologdDictIt,
	"dict/mod0/ipa-neologd-dict.iu": dictMod0IpaNeologdDictIu,
	"dict/mod0/ipa-neologd-dict.iv": dictMod0IpaNeologdDictIv,
	"dict/mod0/ipa-neologd-dict.iw": dictMod0IpaNeologdDictIw,
	"dict/mod0/ipa-neologd-dict.ix": dictMod0IpaNeologdDictIx,
	"dict/mod0/ipa-neologd-dict.iy": dictMod0IpaNeologdDictIy,
	"dict/mod0/ipa-neologd-dict.iz": dictMod0IpaNeologdDictIz,
	"dict/mod0/ipa-neologd-dict.ja": dictMod0IpaNeologdDictJa,
	"dict/mod0/ipa-neologd-dict.jb": dictMod0IpaNeologdDictJb,
	"dict/mod0/ipa-neologd-dict.jc": dictMod0IpaNeologdDictJc,
	"dict/mod0/ipa-neologd-dict.jd": dictMod0IpaNeologdDictJd,
	"dict/mod0/ipa-neologd-dict.je": dictMod0IpaNeologdDictJe,
	"dict/mod0/ipa-neologd-dict.jf": dictMod0IpaNeologdDictJf,
	"dict/mod0/ipa-neologd-dict.jg": dictMod0IpaNeologdDictJg,
	"dict/mod0/ipa-neologd-dict.jh": dictMod0IpaNeologdDictJh,
	"dict/mod0/ipa-neologd-dict.ji": dictMod0IpaNeologdDictJi,
	"dict/mod0/ipa-neologd-dict.jj": dictMod0IpaNeologdDictJj,
	"dict/mod0/ipa-neologd-dict.jk": dictMod0IpaNeologdDictJk,
	"dict/mod0/ipa-neologd-dict.jl": dictMod0IpaNeologdDictJl,
	"dict/mod0/ipa-neologd-dict.jm": dictMod0IpaNeologdDictJm,
	"dict/mod0/ipa-neologd-dict.jn": dictMod0IpaNeologdDictJn,
	"dict/mod0/ipa-neologd-dict.jo": dictMod0IpaNeologdDictJo,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"dict": &bintree{nil, map[string]*bintree{
		"mod0": &bintree{nil, map[string]*bintree{
			"ipa-neologd-dict.aa": &bintree{dictMod0IpaNeologdDictAa, map[string]*bintree{}},
			"ipa-neologd-dict.ab": &bintree{dictMod0IpaNeologdDictAb, map[string]*bintree{}},
			"ipa-neologd-dict.ac": &bintree{dictMod0IpaNeologdDictAc, map[string]*bintree{}},
			"ipa-neologd-dict.ad": &bintree{dictMod0IpaNeologdDictAd, map[string]*bintree{}},
			"ipa-neologd-dict.ae": &bintree{dictMod0IpaNeologdDictAe, map[string]*bintree{}},
			"ipa-neologd-dict.af": &bintree{dictMod0IpaNeologdDictAf, map[string]*bintree{}},
			"ipa-neologd-dict.ag": &bintree{dictMod0IpaNeologdDictAg, map[string]*bintree{}},
			"ipa-neologd-dict.ah": &bintree{dictMod0IpaNeologdDictAh, map[string]*bintree{}},
			"ipa-neologd-dict.ai": &bintree{dictMod0IpaNeologdDictAi, map[string]*bintree{}},
			"ipa-neologd-dict.aj": &bintree{dictMod0IpaNeologdDictAj, map[string]*bintree{}},
			"ipa-neologd-dict.ak": &bintree{dictMod0IpaNeologdDictAk, map[string]*bintree{}},
			"ipa-neologd-dict.al": &bintree{dictMod0IpaNeologdDictAl, map[string]*bintree{}},
			"ipa-neologd-dict.am": &bintree{dictMod0IpaNeologdDictAm, map[string]*bintree{}},
			"ipa-neologd-dict.an": &bintree{dictMod0IpaNeologdDictAn, map[string]*bintree{}},
			"ipa-neologd-dict.ao": &bintree{dictMod0IpaNeologdDictAo, map[string]*bintree{}},
			"ipa-neologd-dict.ap": &bintree{dictMod0IpaNeologdDictAp, map[string]*bintree{}},
			"ipa-neologd-dict.aq": &bintree{dictMod0IpaNeologdDictAq, map[string]*bintree{}},
			"ipa-neologd-dict.ar": &bintree{dictMod0IpaNeologdDictAr, map[string]*bintree{}},
			"ipa-neologd-dict.as": &bintree{dictMod0IpaNeologdDictAs, map[string]*bintree{}},
			"ipa-neologd-dict.at": &bintree{dictMod0IpaNeologdDictAt, map[string]*bintree{}},
			"ipa-neologd-dict.au": &bintree{dictMod0IpaNeologdDictAu, map[string]*bintree{}},
			"ipa-neologd-dict.av": &bintree{dictMod0IpaNeologdDictAv, map[string]*bintree{}},
			"ipa-neologd-dict.aw": &bintree{dictMod0IpaNeologdDictAw, map[string]*bintree{}},
			"ipa-neologd-dict.ax": &bintree{dictMod0IpaNeologdDictAx, map[string]*bintree{}},
			"ipa-neologd-dict.ay": &bintree{dictMod0IpaNeologdDictAy, map[string]*bintree{}},
			"ipa-neologd-dict.az": &bintree{dictMod0IpaNeologdDictAz, map[string]*bintree{}},
			"ipa-neologd-dict.ba": &bintree{dictMod0IpaNeologdDictBa, map[string]*bintree{}},
			"ipa-neologd-dict.bb": &bintree{dictMod0IpaNeologdDictBb, map[string]*bintree{}},
			"ipa-neologd-dict.bc": &bintree{dictMod0IpaNeologdDictBc, map[string]*bintree{}},
			"ipa-neologd-dict.bd": &bintree{dictMod0IpaNeologdDictBd, map[string]*bintree{}},
			"ipa-neologd-dict.be": &bintree{dictMod0IpaNeologdDictBe, map[string]*bintree{}},
			"ipa-neologd-dict.bf": &bintree{dictMod0IpaNeologdDictBf, map[string]*bintree{}},
			"ipa-neologd-dict.bg": &bintree{dictMod0IpaNeologdDictBg, map[string]*bintree{}},
			"ipa-neologd-dict.bh": &bintree{dictMod0IpaNeologdDictBh, map[string]*bintree{}},
			"ipa-neologd-dict.bi": &bintree{dictMod0IpaNeologdDictBi, map[string]*bintree{}},
			"ipa-neologd-dict.bj": &bintree{dictMod0IpaNeologdDictBj, map[string]*bintree{}},
			"ipa-neologd-dict.bk": &bintree{dictMod0IpaNeologdDictBk, map[string]*bintree{}},
			"ipa-neologd-dict.bl": &bintree{dictMod0IpaNeologdDictBl, map[string]*bintree{}},
			"ipa-neologd-dict.bm": &bintree{dictMod0IpaNeologdDictBm, map[string]*bintree{}},
			"ipa-neologd-dict.bn": &bintree{dictMod0IpaNeologdDictBn, map[string]*bintree{}},
			"ipa-neologd-dict.bo": &bintree{dictMod0IpaNeologdDictBo, map[string]*bintree{}},
			"ipa-neologd-dict.bp": &bintree{dictMod0IpaNeologdDictBp, map[string]*bintree{}},
			"ipa-neologd-dict.bq": &bintree{dictMod0IpaNeologdDictBq, map[string]*bintree{}},
			"ipa-neologd-dict.br": &bintree{dictMod0IpaNeologdDictBr, map[string]*bintree{}},
			"ipa-neologd-dict.bs": &bintree{dictMod0IpaNeologdDictBs, map[string]*bintree{}},
			"ipa-neologd-dict.bt": &bintree{dictMod0IpaNeologdDictBt, map[string]*bintree{}},
			"ipa-neologd-dict.bu": &bintree{dictMod0IpaNeologdDictBu, map[string]*bintree{}},
			"ipa-neologd-dict.bv": &bintree{dictMod0IpaNeologdDictBv, map[string]*bintree{}},
			"ipa-neologd-dict.bw": &bintree{dictMod0IpaNeologdDictBw, map[string]*bintree{}},
			"ipa-neologd-dict.bx": &bintree{dictMod0IpaNeologdDictBx, map[string]*bintree{}},
			"ipa-neologd-dict.by": &bintree{dictMod0IpaNeologdDictBy, map[string]*bintree{}},
			"ipa-neologd-dict.bz": &bintree{dictMod0IpaNeologdDictBz, map[string]*bintree{}},
			"ipa-neologd-dict.ca": &bintree{dictMod0IpaNeologdDictCa, map[string]*bintree{}},
			"ipa-neologd-dict.cb": &bintree{dictMod0IpaNeologdDictCb, map[string]*bintree{}},
			"ipa-neologd-dict.cc": &bintree{dictMod0IpaNeologdDictCc, map[string]*bintree{}},
			"ipa-neologd-dict.cd": &bintree{dictMod0IpaNeologdDictCd, map[string]*bintree{}},
			"ipa-neologd-dict.ce": &bintree{dictMod0IpaNeologdDictCe, map[string]*bintree{}},
			"ipa-neologd-dict.cf": &bintree{dictMod0IpaNeologdDictCf, map[string]*bintree{}},
			"ipa-neologd-dict.cg": &bintree{dictMod0IpaNeologdDictCg, map[string]*bintree{}},
			"ipa-neologd-dict.ch": &bintree{dictMod0IpaNeologdDictCh, map[string]*bintree{}},
			"ipa-neologd-dict.ci": &bintree{dictMod0IpaNeologdDictCi, map[string]*bintree{}},
			"ipa-neologd-dict.cj": &bintree{dictMod0IpaNeologdDictCj, map[string]*bintree{}},
			"ipa-neologd-dict.ck": &bintree{dictMod0IpaNeologdDictCk, map[string]*bintree{}},
			"ipa-neologd-dict.cl": &bintree{dictMod0IpaNeologdDictCl, map[string]*bintree{}},
			"ipa-neologd-dict.cm": &bintree{dictMod0IpaNeologdDictCm, map[string]*bintree{}},
			"ipa-neologd-dict.cn": &bintree{dictMod0IpaNeologdDictCn, map[string]*bintree{}},
			"ipa-neologd-dict.co": &bintree{dictMod0IpaNeologdDictCo, map[string]*bintree{}},
			"ipa-neologd-dict.cp": &bintree{dictMod0IpaNeologdDictCp, map[string]*bintree{}},
			"ipa-neologd-dict.cq": &bintree{dictMod0IpaNeologdDictCq, map[string]*bintree{}},
			"ipa-neologd-dict.cr": &bintree{dictMod0IpaNeologdDictCr, map[string]*bintree{}},
			"ipa-neologd-dict.cs": &bintree{dictMod0IpaNeologdDictCs, map[string]*bintree{}},
			"ipa-neologd-dict.ct": &bintree{dictMod0IpaNeologdDictCt, map[string]*bintree{}},
			"ipa-neologd-dict.cu": &bintree{dictMod0IpaNeologdDictCu, map[string]*bintree{}},
			"ipa-neologd-dict.cv": &bintree{dictMod0IpaNeologdDictCv, map[string]*bintree{}},
			"ipa-neologd-dict.cw": &bintree{dictMod0IpaNeologdDictCw, map[string]*bintree{}},
			"ipa-neologd-dict.cx": &bintree{dictMod0IpaNeologdDictCx, map[string]*bintree{}},
			"ipa-neologd-dict.cy": &bintree{dictMod0IpaNeologdDictCy, map[string]*bintree{}},
			"ipa-neologd-dict.cz": &bintree{dictMod0IpaNeologdDictCz, map[string]*bintree{}},
			"ipa-neologd-dict.da": &bintree{dictMod0IpaNeologdDictDa, map[string]*bintree{}},
			"ipa-neologd-dict.db": &bintree{dictMod0IpaNeologdDictDb, map[string]*bintree{}},
			"ipa-neologd-dict.dc": &bintree{dictMod0IpaNeologdDictDc, map[string]*bintree{}},
			"ipa-neologd-dict.dd": &bintree{dictMod0IpaNeologdDictDd, map[string]*bintree{}},
			"ipa-neologd-dict.de": &bintree{dictMod0IpaNeologdDictDe, map[string]*bintree{}},
			"ipa-neologd-dict.df": &bintree{dictMod0IpaNeologdDictDf, map[string]*bintree{}},
			"ipa-neologd-dict.dg": &bintree{dictMod0IpaNeologdDictDg, map[string]*bintree{}},
			"ipa-neologd-dict.dh": &bintree{dictMod0IpaNeologdDictDh, map[string]*bintree{}},
			"ipa-neologd-dict.di": &bintree{dictMod0IpaNeologdDictDi, map[string]*bintree{}},
			"ipa-neologd-dict.dj": &bintree{dictMod0IpaNeologdDictDj, map[string]*bintree{}},
			"ipa-neologd-dict.dk": &bintree{dictMod0IpaNeologdDictDk, map[string]*bintree{}},
			"ipa-neologd-dict.dl": &bintree{dictMod0IpaNeologdDictDl, map[string]*bintree{}},
			"ipa-neologd-dict.dm": &bintree{dictMod0IpaNeologdDictDm, map[string]*bintree{}},
			"ipa-neologd-dict.dn": &bintree{dictMod0IpaNeologdDictDn, map[string]*bintree{}},
			"ipa-neologd-dict.do": &bintree{dictMod0IpaNeologdDictDo, map[string]*bintree{}},
			"ipa-neologd-dict.dp": &bintree{dictMod0IpaNeologdDictDp, map[string]*bintree{}},
			"ipa-neologd-dict.dq": &bintree{dictMod0IpaNeologdDictDq, map[string]*bintree{}},
			"ipa-neologd-dict.dr": &bintree{dictMod0IpaNeologdDictDr, map[string]*bintree{}},
			"ipa-neologd-dict.ds": &bintree{dictMod0IpaNeologdDictDs, map[string]*bintree{}},
			"ipa-neologd-dict.dt": &bintree{dictMod0IpaNeologdDictDt, map[string]*bintree{}},
			"ipa-neologd-dict.du": &bintree{dictMod0IpaNeologdDictDu, map[string]*bintree{}},
			"ipa-neologd-dict.dv": &bintree{dictMod0IpaNeologdDictDv, map[string]*bintree{}},
			"ipa-neologd-dict.dw": &bintree{dictMod0IpaNeologdDictDw, map[string]*bintree{}},
			"ipa-neologd-dict.dx": &bintree{dictMod0IpaNeologdDictDx, map[string]*bintree{}},
			"ipa-neologd-dict.dy": &bintree{dictMod0IpaNeologdDictDy, map[string]*bintree{}},
			"ipa-neologd-dict.dz": &bintree{dictMod0IpaNeologdDictDz, map[string]*bintree{}},
			"ipa-neologd-dict.ea": &bintree{dictMod0IpaNeologdDictEa, map[string]*bintree{}},
			"ipa-neologd-dict.eb": &bintree{dictMod0IpaNeologdDictEb, map[string]*bintree{}},
			"ipa-neologd-dict.ec": &bintree{dictMod0IpaNeologdDictEc, map[string]*bintree{}},
			"ipa-neologd-dict.ed": &bintree{dictMod0IpaNeologdDictEd, map[string]*bintree{}},
			"ipa-neologd-dict.ee": &bintree{dictMod0IpaNeologdDictEe, map[string]*bintree{}},
			"ipa-neologd-dict.ef": &bintree{dictMod0IpaNeologdDictEf, map[string]*bintree{}},
			"ipa-neologd-dict.eg": &bintree{dictMod0IpaNeologdDictEg, map[string]*bintree{}},
			"ipa-neologd-dict.eh": &bintree{dictMod0IpaNeologdDictEh, map[string]*bintree{}},
			"ipa-neologd-dict.ei": &bintree{dictMod0IpaNeologdDictEi, map[string]*bintree{}},
			"ipa-neologd-dict.ej": &bintree{dictMod0IpaNeologdDictEj, map[string]*bintree{}},
			"ipa-neologd-dict.ek": &bintree{dictMod0IpaNeologdDictEk, map[string]*bintree{}},
			"ipa-neologd-dict.el": &bintree{dictMod0IpaNeologdDictEl, map[string]*bintree{}},
			"ipa-neologd-dict.em": &bintree{dictMod0IpaNeologdDictEm, map[string]*bintree{}},
			"ipa-neologd-dict.en": &bintree{dictMod0IpaNeologdDictEn, map[string]*bintree{}},
			"ipa-neologd-dict.eo": &bintree{dictMod0IpaNeologdDictEo, map[string]*bintree{}},
			"ipa-neologd-dict.ep": &bintree{dictMod0IpaNeologdDictEp, map[string]*bintree{}},
			"ipa-neologd-dict.eq": &bintree{dictMod0IpaNeologdDictEq, map[string]*bintree{}},
			"ipa-neologd-dict.er": &bintree{dictMod0IpaNeologdDictEr, map[string]*bintree{}},
			"ipa-neologd-dict.es": &bintree{dictMod0IpaNeologdDictEs, map[string]*bintree{}},
			"ipa-neologd-dict.et": &bintree{dictMod0IpaNeologdDictEt, map[string]*bintree{}},
			"ipa-neologd-dict.eu": &bintree{dictMod0IpaNeologdDictEu, map[string]*bintree{}},
			"ipa-neologd-dict.ev": &bintree{dictMod0IpaNeologdDictEv, map[string]*bintree{}},
			"ipa-neologd-dict.ew": &bintree{dictMod0IpaNeologdDictEw, map[string]*bintree{}},
			"ipa-neologd-dict.ex": &bintree{dictMod0IpaNeologdDictEx, map[string]*bintree{}},
			"ipa-neologd-dict.ey": &bintree{dictMod0IpaNeologdDictEy, map[string]*bintree{}},
			"ipa-neologd-dict.ez": &bintree{dictMod0IpaNeologdDictEz, map[string]*bintree{}},
			"ipa-neologd-dict.fa": &bintree{dictMod0IpaNeologdDictFa, map[string]*bintree{}},
			"ipa-neologd-dict.fb": &bintree{dictMod0IpaNeologdDictFb, map[string]*bintree{}},
			"ipa-neologd-dict.fc": &bintree{dictMod0IpaNeologdDictFc, map[string]*bintree{}},
			"ipa-neologd-dict.fd": &bintree{dictMod0IpaNeologdDictFd, map[string]*bintree{}},
			"ipa-neologd-dict.fe": &bintree{dictMod0IpaNeologdDictFe, map[string]*bintree{}},
			"ipa-neologd-dict.ff": &bintree{dictMod0IpaNeologdDictFf, map[string]*bintree{}},
			"ipa-neologd-dict.fg": &bintree{dictMod0IpaNeologdDictFg, map[string]*bintree{}},
			"ipa-neologd-dict.fh": &bintree{dictMod0IpaNeologdDictFh, map[string]*bintree{}},
			"ipa-neologd-dict.fi": &bintree{dictMod0IpaNeologdDictFi, map[string]*bintree{}},
			"ipa-neologd-dict.fj": &bintree{dictMod0IpaNeologdDictFj, map[string]*bintree{}},
			"ipa-neologd-dict.fk": &bintree{dictMod0IpaNeologdDictFk, map[string]*bintree{}},
			"ipa-neologd-dict.fl": &bintree{dictMod0IpaNeologdDictFl, map[string]*bintree{}},
			"ipa-neologd-dict.fm": &bintree{dictMod0IpaNeologdDictFm, map[string]*bintree{}},
			"ipa-neologd-dict.fn": &bintree{dictMod0IpaNeologdDictFn, map[string]*bintree{}},
			"ipa-neologd-dict.fo": &bintree{dictMod0IpaNeologdDictFo, map[string]*bintree{}},
			"ipa-neologd-dict.fp": &bintree{dictMod0IpaNeologdDictFp, map[string]*bintree{}},
			"ipa-neologd-dict.fq": &bintree{dictMod0IpaNeologdDictFq, map[string]*bintree{}},
			"ipa-neologd-dict.fr": &bintree{dictMod0IpaNeologdDictFr, map[string]*bintree{}},
			"ipa-neologd-dict.fs": &bintree{dictMod0IpaNeologdDictFs, map[string]*bintree{}},
			"ipa-neologd-dict.ft": &bintree{dictMod0IpaNeologdDictFt, map[string]*bintree{}},
			"ipa-neologd-dict.fu": &bintree{dictMod0IpaNeologdDictFu, map[string]*bintree{}},
			"ipa-neologd-dict.fv": &bintree{dictMod0IpaNeologdDictFv, map[string]*bintree{}},
			"ipa-neologd-dict.fw": &bintree{dictMod0IpaNeologdDictFw, map[string]*bintree{}},
			"ipa-neologd-dict.fx": &bintree{dictMod0IpaNeologdDictFx, map[string]*bintree{}},
			"ipa-neologd-dict.fy": &bintree{dictMod0IpaNeologdDictFy, map[string]*bintree{}},
			"ipa-neologd-dict.fz": &bintree{dictMod0IpaNeologdDictFz, map[string]*bintree{}},
			"ipa-neologd-dict.ga": &bintree{dictMod0IpaNeologdDictGa, map[string]*bintree{}},
			"ipa-neologd-dict.gb": &bintree{dictMod0IpaNeologdDictGb, map[string]*bintree{}},
			"ipa-neologd-dict.gc": &bintree{dictMod0IpaNeologdDictGc, map[string]*bintree{}},
			"ipa-neologd-dict.gd": &bintree{dictMod0IpaNeologdDictGd, map[string]*bintree{}},
			"ipa-neologd-dict.ge": &bintree{dictMod0IpaNeologdDictGe, map[string]*bintree{}},
			"ipa-neologd-dict.gf": &bintree{dictMod0IpaNeologdDictGf, map[string]*bintree{}},
			"ipa-neologd-dict.gg": &bintree{dictMod0IpaNeologdDictGg, map[string]*bintree{}},
			"ipa-neologd-dict.gh": &bintree{dictMod0IpaNeologdDictGh, map[string]*bintree{}},
			"ipa-neologd-dict.gi": &bintree{dictMod0IpaNeologdDictGi, map[string]*bintree{}},
			"ipa-neologd-dict.gj": &bintree{dictMod0IpaNeologdDictGj, map[string]*bintree{}},
			"ipa-neologd-dict.gk": &bintree{dictMod0IpaNeologdDictGk, map[string]*bintree{}},
			"ipa-neologd-dict.gl": &bintree{dictMod0IpaNeologdDictGl, map[string]*bintree{}},
			"ipa-neologd-dict.gm": &bintree{dictMod0IpaNeologdDictGm, map[string]*bintree{}},
			"ipa-neologd-dict.gn": &bintree{dictMod0IpaNeologdDictGn, map[string]*bintree{}},
			"ipa-neologd-dict.go": &bintree{dictMod0IpaNeologdDictGo, map[string]*bintree{}},
			"ipa-neologd-dict.gp": &bintree{dictMod0IpaNeologdDictGp, map[string]*bintree{}},
			"ipa-neologd-dict.gq": &bintree{dictMod0IpaNeologdDictGq, map[string]*bintree{}},
			"ipa-neologd-dict.gr": &bintree{dictMod0IpaNeologdDictGr, map[string]*bintree{}},
			"ipa-neologd-dict.gs": &bintree{dictMod0IpaNeologdDictGs, map[string]*bintree{}},
			"ipa-neologd-dict.gt": &bintree{dictMod0IpaNeologdDictGt, map[string]*bintree{}},
			"ipa-neologd-dict.gu": &bintree{dictMod0IpaNeologdDictGu, map[string]*bintree{}},
			"ipa-neologd-dict.gv": &bintree{dictMod0IpaNeologdDictGv, map[string]*bintree{}},
			"ipa-neologd-dict.gw": &bintree{dictMod0IpaNeologdDictGw, map[string]*bintree{}},
			"ipa-neologd-dict.gx": &bintree{dictMod0IpaNeologdDictGx, map[string]*bintree{}},
			"ipa-neologd-dict.gy": &bintree{dictMod0IpaNeologdDictGy, map[string]*bintree{}},
			"ipa-neologd-dict.gz": &bintree{dictMod0IpaNeologdDictGz, map[string]*bintree{}},
			"ipa-neologd-dict.ha": &bintree{dictMod0IpaNeologdDictHa, map[string]*bintree{}},
			"ipa-neologd-dict.hb": &bintree{dictMod0IpaNeologdDictHb, map[string]*bintree{}},
			"ipa-neologd-dict.hc": &bintree{dictMod0IpaNeologdDictHc, map[string]*bintree{}},
			"ipa-neologd-dict.hd": &bintree{dictMod0IpaNeologdDictHd, map[string]*bintree{}},
			"ipa-neologd-dict.he": &bintree{dictMod0IpaNeologdDictHe, map[string]*bintree{}},
			"ipa-neologd-dict.hf": &bintree{dictMod0IpaNeologdDictHf, map[string]*bintree{}},
			"ipa-neologd-dict.hg": &bintree{dictMod0IpaNeologdDictHg, map[string]*bintree{}},
			"ipa-neologd-dict.hh": &bintree{dictMod0IpaNeologdDictHh, map[string]*bintree{}},
			"ipa-neologd-dict.hi": &bintree{dictMod0IpaNeologdDictHi, map[string]*bintree{}},
			"ipa-neologd-dict.hj": &bintree{dictMod0IpaNeologdDictHj, map[string]*bintree{}},
			"ipa-neologd-dict.hk": &bintree{dictMod0IpaNeologdDictHk, map[string]*bintree{}},
			"ipa-neologd-dict.hl": &bintree{dictMod0IpaNeologdDictHl, map[string]*bintree{}},
			"ipa-neologd-dict.hm": &bintree{dictMod0IpaNeologdDictHm, map[string]*bintree{}},
			"ipa-neologd-dict.hn": &bintree{dictMod0IpaNeologdDictHn, map[string]*bintree{}},
			"ipa-neologd-dict.ho": &bintree{dictMod0IpaNeologdDictHo, map[string]*bintree{}},
			"ipa-neologd-dict.hp": &bintree{dictMod0IpaNeologdDictHp, map[string]*bintree{}},
			"ipa-neologd-dict.hq": &bintree{dictMod0IpaNeologdDictHq, map[string]*bintree{}},
			"ipa-neologd-dict.hr": &bintree{dictMod0IpaNeologdDictHr, map[string]*bintree{}},
			"ipa-neologd-dict.hs": &bintree{dictMod0IpaNeologdDictHs, map[string]*bintree{}},
			"ipa-neologd-dict.ht": &bintree{dictMod0IpaNeologdDictHt, map[string]*bintree{}},
			"ipa-neologd-dict.hu": &bintree{dictMod0IpaNeologdDictHu, map[string]*bintree{}},
			"ipa-neologd-dict.hv": &bintree{dictMod0IpaNeologdDictHv, map[string]*bintree{}},
			"ipa-neologd-dict.hw": &bintree{dictMod0IpaNeologdDictHw, map[string]*bintree{}},
			"ipa-neologd-dict.hx": &bintree{dictMod0IpaNeologdDictHx, map[string]*bintree{}},
			"ipa-neologd-dict.hy": &bintree{dictMod0IpaNeologdDictHy, map[string]*bintree{}},
			"ipa-neologd-dict.hz": &bintree{dictMod0IpaNeologdDictHz, map[string]*bintree{}},
			"ipa-neologd-dict.ia": &bintree{dictMod0IpaNeologdDictIa, map[string]*bintree{}},
			"ipa-neologd-dict.ib": &bintree{dictMod0IpaNeologdDictIb, map[string]*bintree{}},
			"ipa-neologd-dict.ic": &bintree{dictMod0IpaNeologdDictIc, map[string]*bintree{}},
			"ipa-neologd-dict.id": &bintree{dictMod0IpaNeologdDictId, map[string]*bintree{}},
			"ipa-neologd-dict.ie": &bintree{dictMod0IpaNeologdDictIe, map[string]*bintree{}},
			"ipa-neologd-dict.if": &bintree{dictMod0IpaNeologdDictIf, map[string]*bintree{}},
			"ipa-neologd-dict.ig": &bintree{dictMod0IpaNeologdDictIg, map[string]*bintree{}},
			"ipa-neologd-dict.ih": &bintree{dictMod0IpaNeologdDictIh, map[string]*bintree{}},
			"ipa-neologd-dict.ii": &bintree{dictMod0IpaNeologdDictIi, map[string]*bintree{}},
			"ipa-neologd-dict.ij": &bintree{dictMod0IpaNeologdDictIj, map[string]*bintree{}},
			"ipa-neologd-dict.ik": &bintree{dictMod0IpaNeologdDictIk, map[string]*bintree{}},
			"ipa-neologd-dict.il": &bintree{dictMod0IpaNeologdDictIl, map[string]*bintree{}},
			"ipa-neologd-dict.im": &bintree{dictMod0IpaNeologdDictIm, map[string]*bintree{}},
			"ipa-neologd-dict.in": &bintree{dictMod0IpaNeologdDictIn, map[string]*bintree{}},
			"ipa-neologd-dict.io": &bintree{dictMod0IpaNeologdDictIo, map[string]*bintree{}},
			"ipa-neologd-dict.ip": &bintree{dictMod0IpaNeologdDictIp, map[string]*bintree{}},
			"ipa-neologd-dict.iq": &bintree{dictMod0IpaNeologdDictIq, map[string]*bintree{}},
			"ipa-neologd-dict.ir": &bintree{dictMod0IpaNeologdDictIr, map[string]*bintree{}},
			"ipa-neologd-dict.is": &bintree{dictMod0IpaNeologdDictIs, map[string]*bintree{}},
			"ipa-neologd-dict.it": &bintree{dictMod0IpaNeologdDictIt, map[string]*bintree{}},
			"ipa-neologd-dict.iu": &bintree{dictMod0IpaNeologdDictIu, map[string]*bintree{}},
			"ipa-neologd-dict.iv": &bintree{dictMod0IpaNeologdDictIv, map[string]*bintree{}},
			"ipa-neologd-dict.iw": &bintree{dictMod0IpaNeologdDictIw, map[string]*bintree{}},
			"ipa-neologd-dict.ix": &bintree{dictMod0IpaNeologdDictIx, map[string]*bintree{}},
			"ipa-neologd-dict.iy": &bintree{dictMod0IpaNeologdDictIy, map[string]*bintree{}},
			"ipa-neologd-dict.iz": &bintree{dictMod0IpaNeologdDictIz, map[string]*bintree{}},
			"ipa-neologd-dict.ja": &bintree{dictMod0IpaNeologdDictJa, map[string]*bintree{}},
			"ipa-neologd-dict.jb": &bintree{dictMod0IpaNeologdDictJb, map[string]*bintree{}},
			"ipa-neologd-dict.jc": &bintree{dictMod0IpaNeologdDictJc, map[string]*bintree{}},
			"ipa-neologd-dict.jd": &bintree{dictMod0IpaNeologdDictJd, map[string]*bintree{}},
			"ipa-neologd-dict.je": &bintree{dictMod0IpaNeologdDictJe, map[string]*bintree{}},
			"ipa-neologd-dict.jf": &bintree{dictMod0IpaNeologdDictJf, map[string]*bintree{}},
			"ipa-neologd-dict.jg": &bintree{dictMod0IpaNeologdDictJg, map[string]*bintree{}},
			"ipa-neologd-dict.jh": &bintree{dictMod0IpaNeologdDictJh, map[string]*bintree{}},
			"ipa-neologd-dict.ji": &bintree{dictMod0IpaNeologdDictJi, map[string]*bintree{}},
			"ipa-neologd-dict.jj": &bintree{dictMod0IpaNeologdDictJj, map[string]*bintree{}},
			"ipa-neologd-dict.jk": &bintree{dictMod0IpaNeologdDictJk, map[string]*bintree{}},
			"ipa-neologd-dict.jl": &bintree{dictMod0IpaNeologdDictJl, map[string]*bintree{}},
			"ipa-neologd-dict.jm": &bintree{dictMod0IpaNeologdDictJm, map[string]*bintree{}},
			"ipa-neologd-dict.jn": &bintree{dictMod0IpaNeologdDictJn, map[string]*bintree{}},
			"ipa-neologd-dict.jo": &bintree{dictMod0IpaNeologdDictJo, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

